
import pandas as pd
import numpy as np
GENE_NAME_STD_MAP = pd.read_csv('./hgnc_alternative_symbol_mapping.csv', index_col=0)
ALL_TCGA_PROJ_IDS = ['TCGA-OV', 'TCGA-THCA', 'TCGA-LUAD', 'TCGA-PCPG', 'TCGA-ACC',
       'TCGA-LIHC', 'TCGA-SKCM', 'TCGA-SARC', 'TCGA-LUSC', 'TCGA-LAML',
       'TCGA-UCEC', 'TCGA-KIRC', 'TCGA-BLCA', 'TCGA-READ', 'TCGA-CESC',
       'TCGA-PRAD', 'TCGA-PAAD', 'TCGA-HNSC', 'TCGA-LGG', 'TCGA-THYM',
       'TCGA-DLBC', 'TCGA-UCS', 'TCGA-CHOL', 'TCGA-MESO', 'TCGA-KICH',
       'TCGA-UVM', 'TCGA-COAD', 'TCGA-KIRP', 'TCGA-ESCA', 'TCGA-STAD',
       'TCGA-GBM', 'TCGA-TGCT', 'TCGA-BRCA']
NOT_SOLID_TUMOR = [
    'TCGA-LAML', 'TCGA-DLBC',
    'TCGA-LCML', 'TCGA-FPPP', 'TCGA-CNTL', 'TCGA-CNTL'
]

ONCOKB_CANCER_TYPE_MAPPING = {
    'B-Lymphoblastic Leukemia/Lymphoma': None, 
    'Chronic Myelogenous Leukemia': 'TCGA-LCML', 
    'Breast Cancer': "TCGA-BRCA",
    'Anaplastic Large-Cell Lymphoma ALK Positive': None,
    'Inflammatory Myofibroblastic Tumor': None,
    'Non-Small Cell Lung Cancer': ["TCGA-LUAD", "TCGA-LUSC"],
    'Prostate Cancer, NOS, Prostate Cancer': "TCGA-PRAD",
    'Low-Grade Glioma, NOS': "TCGA-LGG",
    'Erdheim-Chester Disease': None,
    'Melanoma': "TCGA-SKCM",
    'All Solid Tumors (excluding Colorectal Cancer)': np.array(list(set(ALL_TCGA_PROJ_IDS)-set(['TCGA-COAD','TCGA-READ'])-set(NOT_SOLID_TUMOR))),
    'Anaplastic Thyroid Cancer': None,
    'Biliary Tract Cancer, NOS': "TCGA-CHOL",
    'Colorectal Cancer': ["TCGA-COAD", "TCGA-READ"],
    'Ovarian Cancer, Ovary/Fallopian Tube, Peritoneal Serous Carcinoma': "TCGA-OV",
    'Esophagogastric Cancer': ["TCGA-ESCA", "TCGA-STAD"],
    'Follicular Lymphoma': None,
    'Myeloid/Lymphoid Neoplasms with Eosinophilia and Rearrangement of  PDGFRA/PDGFRB or FGFR1 or with PCM1-JAK2': None,
    'Cholangiocarcinoma': "TCGA-CHOL",
    'Bladder Cancer': "TCGA-BLCA",
    'Acute Myeloid Leukemia': "TCGA-LAML",
    'Intrahepatic Cholangiocarcinoma, Cholangiocarcinoma': "TCGA-CHOL",
    'Myelodysplastic Syndromes': None,
    'Oligodendroglioma, Astrocytoma': "TCGA-LGG",
    'Mastocytosis': None,
    'Gastrointestinal Stromal Tumor': None,
    'Acute Leukemias of Ambiguous Lineage': None,
    'Neurofibroma': None,
    'Pancreatic Adenocarcinoma': "TCGA-PAAD",
    'All Solid Tumors': np.array(list(set(ALL_TCGA_PROJ_IDS)-set(NOT_SOLID_TUMOR))),
    'Endometrial Cancer': "TCGA-UCEC",
    'Dermatofibrosarcoma Protuberans': None,
    'Chronic Eosinophilic Leukemia, NOS': None,
    'Myelodysplastic/Myeloproliferative Neoplasms': None,
    'APL with PML-RARA': None,
    'Thyroid Cancer': "TCGA-THCA",
    'Medullary Thyroid Cancer': None,
    'Epithelioid Sarcoma': "TCGA-SARC",
    'Encapsulated Glioma': "TCGA-LGG",
    'Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma': None,
    'Langerhans Cell Histiocytosis': None,
    'Rosai-Dorfman Disease': None,
    'Pilocytic Astrocytoma': None,
    'Diffuse Glioma (excluding Diffuse Intrinsic Pontine Glioma, Diffuse Astrocytoma, Anaplastic Oligodendroglioma, Oligodendroglioma, Oligoastrocytoma, Astrocytoma)': "TCGA-LGG",
    'Hairy Cell Leukemia': None,
    'Pleomorphic Xanthoastrocytoma, Pilocytic Astrocytoma, Ganglioglioma': None,
    'Pancreatic Adenocarcinoma, Acinar Cell Carcinoma of the Pancreas': None, 
    'Uterine Sarcoma': None,
    'Salivary Gland Cancer': None,
    'Uterine Serous Carcinoma/Uterine Papillary Serous Carcinoma': "TCGA-UCEC",
    'Cervical Cancer': "TCGA-CESC",
    'Chondrosarcoma': None,
    'Ampullary Cancer': None,
    'Hepatobiliary Cancer': ["TCGA-LIHC", "TCGA-CHOL"],
    'Small Bowel Cancer': None,
    'Ovarian Cancer, Endometrial Cancer': ["TCGA-OV", "TCGA-UCEC"],
    'Neuroblastoma': None,
    'Histiocytosis': None,
    'Ovarian Cancer': "TCGA-OV",
    'Bladder Urothelial Carcinoma': "TCGA-BLCA",
    'Head and Neck Squamous Cell Carcinoma': "TCGA-HNSC",
    'Glioma': ["TCGA-GBM", "TCGA-LGG"],
    'Tubular Adenoma of the Colon, Esophagogastric Cancer, Anal Cancer, Gastrointestinal Neuroendocrine Tumors of the Esophagus/Stomach': None,
    'Melanoma, Non-Small Cell Lung Cancer, Low-Grade Serous Ovarian Cancer': ["TCGA-SKCM", "TCGA-LUAD", "TCGA-LUSC"],
    'Dedifferentiated Liposarcoma': "TCGA-SARC",
    'Intimal Sarcoma': None,
    'Well-Differentiated Liposarcoma': "TCGA-SARC",
    'Renal Cell Carcinoma': ["TCGA-KIRC", 'TCGA-KIRP', 'TCGA-KICH'],
    'Medulloblastoma': None,
    'Esophageal Adenocarcinoma': "TCGA-ESCA",
    'Perivascular Epithelioid Cell Tumor, Uterine Perivascular Epithelioid Cell Tumor': None,
    'Dedifferentiated Liposarcoma, Well-Differentiated Liposarcoma': "TCGA-SARC",
    'All Solid Tumors (excluding Bladder Cancer, Cholangiocarcinoma)': np.array(list(set(ALL_TCGA_PROJ_IDS)-set(['TCGA-CHOL','TCGA-BLCA'])-set(NOT_SOLID_TUMOR))),
    'All Solid Tumors (excluding Bladder Cancer)': np.array(list(set(ALL_TCGA_PROJ_IDS)-set(['TCGA-BLCA'])-set(NOT_SOLID_TUMOR))),
    'Ewing Sarcoma, Ewing Sarcoma of Soft Tissue': None,
    'Chronic Myelomonocytic Leukemia, Myelodysplastic Syndromes': None,
    'All Liquid Tumors': ["TCGA-LAML", "TCGA-DLBC"],
    'AML with Biallelic Mutations of CEBPA': 'TCGA-LAML',
    'AML with Myelodysplasia-Related Changes': None,  
    'AML with t(8;21)(q22;q22.1);RUNX1-RUNX1T1': 'TCGA-LAML',
    'Anaplastic Large-Cell Lymphoma ALK Negative': None,
    'B-Lymphoblastic Leukemia/Lymphoma, BCR-ABL1 Like': None,
    'Chronic Myelomonocytic Leukemia': None,
    'Essential Thrombocythemia': None,
    'Lymphoplasmacytic Lymphoma': None,
    'MDS/MPN with Ring Sideroblasts and Thrombocytosis': None,
    'Mantle Cell Lymphoma': None,
    'Myeloproliferative Neoplasms': None,
    'Plasma Cell Myeloma': None,
    'Polycythemia Vera': None,
    'Primary Myelofibrosis': None,
    'T-Lymphoblastic Leukemia/Lymphoma': None,
    'Therapy-Related Myeloid Neoplasms': None
}



CIVIC_DISEASE_MAPPING = {
    'Lymphoid Leukemia': "nan",
    'Gastrointestinal Stromal Tumor': "nan",
    'Acute Myeloid Leukemia': "TCGA-LAML",
    'Chronic Myeloid Leukemia': "nan",
    'Bone Marrow Cancer': "nan",
    'Acute Leukemia': "nan",
    'Melanoma': "TCGA-SKCM",
    'Lung Non-small Cell Carcinoma': ["TCGA-LUAD", "TCGA-LUSC"],
    'Polycythemia Vera': "nan",
    'Colorectal Cancer': ["TCGA-COAD", "TCGA-READ"],
    'Inflammatory Myofibroblastic Tumor': "nan",
    'Neuroblastoma': "nan",
    'Medullary Thyroid Carcinoma': "nan",
    'Thyroid Cancer': "TCGA-THCA",
    'Papillary Thyroid Carcinoma': "TCGA-THCA",
    'Bladder Carcinoma': "TCGA-BLCA",
    'Glioblastoma': "TCGA-GBM",
    'Ovarian Cancer': "TCGA-OV",
    'Stomach Cancer': "TCGA-STAD",
    'Breast Cancer': "TCGA-BRCA",
    'Lung Cancer': ["TCGA-LUAD", "TCGA-LUSC"],
    'Lung Adenocarcinoma': "TCGA-LUAD",
    'T-cell Lymphoblastic Leukemia/lymphoma': "nan",
    'Estrogen-receptor Positive Breast Cancer': "TCGA-BRCA",
    'Cholangiocarcinoma': "TCGA-CHOL",
    'Malignant Anus Melanoma': "nan",
    'Acute Promyelocytic Leukemia': "TCGA-LAML", 
    'Invasive Bladder Transitional Cell Carcinoma': "TCGA-BLCA",
    'Malignant Astrocytoma': "TCGA-GBM",
    'Myelodysplastic Syndrome': "nan",
    'Head And Neck Squamous Cell Carcinoma': "TCGA-HNSC",
    'Mantle Cell Lymphoma': "nan",
    'Gastric Adenosquamous Carcinoma': "nan",
    'Multiple Myeloma': "nan",
    'Acute Lymphoblastic Leukemia': "nan",
    'Fibrolamellar Carcinoma': "nan",
    'Diffuse Large B-cell Lymphoma': "TCGA-DLBC",
    'Prostate Cancer': "TCGA-PRAD",
    'Ovarian Carcinoma': "TCGA-OV",
    'Clear Cell Renal Cell Carcinoma': "TCGA-KIRC",
    'Ewing Sarcoma': "nan",
    'Follicular Lymphoma': "nan",
    'Chronic Lymphocytic Leukemia': "nan",
    'Colon Carcinoma': "TCGA-COAD",
    'Prostate Carcinoma': "TCGA-PRAD",
    'Cancer': ALL_TCGA_PROJ_IDS,
    'Hematologic Cancer': ["TCGA-LAML", "TCGA-DLBC"],
    'Cervical Adenocarcinoma': "TCGA-CESC",
    'Uveal Melanoma': "TCGA-UVM",
    'Renal Cell Carcinoma': ["TCGA-KIRC", "TCGA-KICH", "TCGA-KIRP"],  
  
    'Epithelial Ovarian Cancer': "TCGA-OV",
    'T-cell Acute Lymphoblastic Leukemia': "nan",
    "Barrett's Adenocarcinoma": "TCGA-ESCA",  
  
    'Cervical Squamous Cell Carcinoma': "TCGA-CESC",
    'Brain Glioblastoma Multiforme': "TCGA-GBM",
    'Ovarian Granulosa Cell Tumor': "nan",
    'B-lymphoblastic Leukemia/lymphoma': "nan",
    'Thymic Carcinoma': "nan",  
  
    'Oligodendroglioma': "TCGA-LGG",
    'Follicular Thyroid Carcinoma': "nan",
    'Gastric Adenocarcinoma': "TCGA-STAD",
    'Prostate Adenocarcinoma': "TCGA-PRAD",
    'Pancreatic Adenocarcinoma': "TCGA-PAAD",
    'Small-cell Carcinoma Of The Ovary Of Hypercalcemic Type': "nan",
    'Acral Lentiginous Melanoma': "TCGA-SKCM",
    'Skin Melanoma': "TCGA-SKCM",
    'Esophagus Squamous Cell Carcinoma': "TCGA-ESCA",
    'Myeloid Neoplasm': "TCGA-LAML",
    'Her2-receptor Positive Breast Cancer': "TCGA-BRCA",
    'Ovarian Serous Carcinoma': "TCGA-OV",
    'Peripheral T-cell Lymphoma': "nan",
    'Oral Squamous Cell Carcinoma': "TCGA-HNSC",
    'Peritoneal Mesothelioma': "nan",
    'Colon Cancer': "TCGA-COAD",
    'Parietal Lobe Ependymoma': "nan",
    'Cervical Cancer': "TCGA-CESC",
    'Osteosarcoma': "nan",
    'Lung Squamous Cell Carcinoma': "TCGA-LUSC",
    'Endometrial Cancer': "TCGA-UCEC",
    'Merkel Cell Carcinoma': "nan",
    'Medulloblastoma': "nan",
    'Basal Cell Carcinoma': "nan",
    'Oropharynx Cancer': "TCGA-HNSC",
    'Papillary Renal Cell Carcinoma': "TCGA-KIRP",
    'Head And Neck Carcinoma': "TCGA-HNSC",
    'Malignant Pleural Mesothelioma': "TCGA-MESO",
    'Ewing Sarcoma Of Bone': "nan",
    'Atypical Chronic Myeloid Leukemia, BCR-ABL1 Negative': "nan",
    'Endometrial Carcinoma': "TCGA-UCEC",
    'Pancreatic Ductal Adenocarcinoma': "TCGA-PAAD",
    'Uterine Corpus Endometrial Carcinoma': "TCGA-UCEC",
    'Esophageal Carcinoma': "TCGA-ESCA",
    'Pancreatic Carcinoma': "TCGA-PAAD",
    'Sarcoma': "TCGA-SARC",
    'Hepatocellular Carcinoma': "TCGA-LIHC",
    'Malignant Mesothelioma': "TCGA-MESO",
    'Bile Duct Adenocarcinoma': "TCGA-CHOL",
    'T-cell Large Granular Lymphocyte Leukemia': "nan",
    'Brain Glioma': ["TCGA-GBM", "TCGA-LGG"],
    'Lymphoplasmacytic Lymphoma': "nan",
    'Adrenocortical Carcinoma': "TCGA-ACC",
    'Renal Carcinoma': ["TCGA-KIRC", "TCGA-KICH", "TCGA-KIRP"],
    'Lung Small Cell Carcinoma': "nan",
    'Lung Carcinoma': ["TCGA-LUAD", "TCGA-LUSC"],
    'Meningioma': "nan",
    'Synovial Sarcoma': "TCGA-SARC",
    'Malignant Peripheral Nerve Sheath Tumor': "TCGA-SARC",
    'Skin Squamous Cell Carcinoma': "nan",
    'Endometrial Serous Adenocarcinoma': "TCGA-UCEC",
    'Myeloproliferative Neoplasm': "nan",
    'Angiosarcoma': "nan",
    'Thyroid Gland Carcinoma': "TCGA-THCA",
    'Lung Acinar Adenocarcinoma': "TCGA-LUAD",
    'Hairy Cell Leukemia': "nan",
    'Colon Mucinous Adenocarcinoma': "TCGA-COAD",
    'Inflammatory Breast Carcinoma': "TCGA-BRCA",
    'Head And Neck Cancer': "TCGA-HNSC",
    'Pancreatic Cancer': "TCGA-PAAD",
    'Colorectal Adenocarcinoma': ["TCGA-COAD", "TCGA-READ"],
    'Anaplastic Large Cell Lymphoma': "nan",
    'Myelofibrosis': "nan",
    'Stomach Carcinoma': "TCGA-STAD",
    'Pancreatic Ductal Carcinoma': "TCGA-PAAD",
    'B-lymphoblastic Leukemia/lymphoma, BCR-ABL1-like': "nan",
    'Malignant Exocrine Pancreas Neoplasm': "TCGA-PAAD",
    'Laryngeal Carcinoma': "TCGA-HNSC",
    'Endometrial Adenocarcinoma': "TCGA-UCEC",
    'Liposarcoma': "TCGA-SARC",
    'Chronic Neutrophilic Leukemia': "nan",
    'Chronic Leukemia': "nan",
    'Chronic Myelomonocytic Leukemia': "nan",
    'Gastrointestinal Neuroendocrine Tumor': "nan",
    'Myeloid And Lymphoid Neoplasms With Eosinophilia And Abnormalities Of PDGFRA, PDGFRB, And FGFR1': "nan",
    'Transitional Cell Carcinoma': "TCGA-BLCA",
    'Bronchiolo-alveolar Adenocarcinoma': "TCGA-LUAD",
    'Mucosal Melanoma': "nan",
    'Essential Thrombocythemia': "nan",
    'Papillary Adenocarcinoma': "nan",
    "Sezary's Disease": "nan",
    'B-cell Adult Acute Lymphocytic Leukemia': "nan",
    'Langerhans-cell Histiocytosis': "nan",
    'Pseudomyxoma Peritonei': "nan",
    'Chuvash Polycythemia': "nan",
    'Peutz-Jeghers Syndrome': "nan",
    'Colon Adenocarcinoma': "TCGA-COAD",
    'Mixed Fibrolamellar Hepatocellular Carcinoma': "nan",
    'Spindle Cell Sarcoma': "TCGA-SARC",
    'Triple-receptor Negative Breast Cancer': "TCGA-BRCA",
    "Scrotum Paget's Disease": "nan",
    'Oncocytic Carcinoma Of The Thyroid': "nan",
    'Female Reproductive Organ Cancer': ["TCGA-BRCA", "TCGA-OV"],
    'Systemic Mastocytosis': "nan",
    'Ovarian Serous Cystadenocarcinoma': "TCGA-OV",
    'Rhabdoid Cancer': "nan",
    'Rectum Cancer': "TCGA-READ",
    'Her2-receptor Negative Breast Cancer': "TCGA-BRCA",
    'Tuberous Sclerosis': "nan",
    'Myxoid Liposarcoma': "TCGA-SARC",
    'NUT Midline Carcinoma': "nan",
    'Bone Epithelioid Hemangioma': "nan",
    'Malignant Epithelioid Hemangioendothelioma': "nan",
    'Villous Adenoma': "nan",
    'Von Hippel-Lindau Disease': "nan",
    'Pericytoma With T(7;12)': "nan",
    'Mammary Analogue Secretory Carcinoma': "nan",
    'Dermatofibrosarcoma Protuberans': "nan",
    'Lynch Syndrome': "nan",
    'Endometrial Hyperplasia': "nan",
    'PTEN Hamartoma Tumor Syndrome': "nan",
    'Chromophobe Renal Cell Carcinoma': "TCGA-KICH",
    'Plexiform Neurofibroma': "nan",
    'Chordoma': "nan",
    'Intrahepatic Cholangiocarcinoma': "TCGA-CHOL",
    'Breast Carcinoma': "TCGA-BRCA",
    'High Grade Glioma': "TCGA-GBM",
    'Bladder Urothelial Carcinoma': "TCGA-BLCA",
    'Esophageal Cancer': "TCGA-ESCA",
    'Neuroendocrine Tumor': "nan",
    'Solid Tumor': list(set(ALL_TCGA_PROJ_IDS) - {'TCGA-LAML','TCGA-DLBC'}), 
    'Leukemia': "nan",
    'Desmoid Tumor': "nan",
    'Ovarian Clear Cell Carcinoma': "nan",
    'Cervix Carcinoma': "TCGA-CESC",
    'Breast Tubular Carcinoma': "TCGA-BRCA",
    'Childhood Pilocytic Astrocytoma': "nan",
    'Endometrioid Ovary Carcinoma': "nan",
    'Diffuse Midline Glioma, H3 K27M-mutant': "nan",
    'Adrenal Carcinoma': "TCGA-ACC",
    'Vulva Squamous Cell Carcinoma': "nan",
    'Sertoli-Leydig Cell Tumor': "nan",
    'Ureter Small Cell Carcinoma': "nan",
    'Glandular Pattern Ovarian Yolk Sac Tumor': "nan",
    'Anaplastic Thyroid Carcinoma': "nan",
    'Laryngeal Squamous Cell Carcinoma': "TCGA-HNSC",
    'Biliary Tract Cancer': "TCGA-CHOL",
    'Salivary Gland Carcinoma': "nan",
    'Ovarian Sex-cord Stromal Tumor': "nan",
    'Vagina Sarcoma': "nan",
    'Epithelioid Inflammatory Myofibroblastic Sarcoma': "nan",
    'Congenital Fibrosarcoma': "nan",
    'Adrenal Gland Pheochromocytoma': "TCGA-PCPG",
    'Salivary Gland Cancer': "nan",
    'Lipofibromatosis-like Neural Tumor': "nan",
    'Paraganglioma': "TCGA-PCPG",
    'Juvenile Polyposis Syndrome': "nan",
    'Chondroblastoma': "nan",
    'Bone Giant Cell Tumor': "nan",
    'Breast Secretory Carcinoma': "nan",
    'Adult T-cell Leukemia/lymphoma': "nan",
    'Childhood B-cell Acute Lymphoblastic Leukemia': "nan",
    'Mesenchymal Chondrosarcoma': "nan",
    'Alveolar Rhabdomyosarcoma': "nan",
    'Juvenile Myelomonocytic Leukemia': "nan",
    'Pilocytic Astrocytoma': "nan",
    'Lymphoma': "nan",
    'Childhood Low-grade Glioma': "nan",
    np.nan: "nan",
    'Retinoblastoma': "nan",
    'B-lymphoblastic Leukemia/lymphoma With PAX5 P80R': "nan",
    'Urinary Bladder Cancer': "TCGA-BLCA",
    'Langerhans Cell Sarcoma': "nan",
    'Glioma': ["TCGA-GBM", "TCGA-LGG"],
    'Chondrosarcoma': "nan",
    'Histiocytic And Dendritic Cell Cancer': "nan",
    'Glioblastoma Proneural Subtype': "TCGA-GBM",
    'Adenosquamous Lung Carcinoma': ["TCGA-LUAD", "TCGA-LUSC"],  
  
    'Childhood Acute Lymphocytic Leukemia': "nan",
    'Rhabdomyosarcoma': "nan",
    'Childhood Medulloblastoma': "nan",
    'B-cell Acute Lymphoblastic Leukemia': "nan",
    'Adult Spinal Cord Ependymoma': "nan",
    'Cholangiolocellular Carcinoma': "TCGA-CHOL",  
  
    'Chronic Lymphocytic Leukemia/small Lymphocytic Lymphoma': "nan",
    'Spindle Cell Rhabdomyosarcoma': "nan",
    'Medulloblastoma SHH Activated': "nan",
    'Castration-resistant Prostate Carcinoma': "TCGA-PRAD",
    'Astroblastoma, MN1-altered': "nan",
    'B-lymphoblastic Leukemia/lymphoma With ETV6-RUNX1': "nan",
    'Supratentorial Ependymoma, ZFTA Fusion-positive': "nan",
    'Ovary Serous Adenocarcinoma': "TCGA-OV",
    'Atypical Teratoid Rhabdoid Tumor': "nan",
    'Spitzoid Melanoma': "TCGA-SKCM",
    "Renal Wilms' Tumor": "nan",
    'CIC-rearranged Sarcoma': "nan",
    'Pancreatic Endocrine Carcinoma': "nan",
    'Diffuse Glioma, H3 G34 Mutant': "nan",
    'Childhood Ependymoma': "nan",
    'Alveolar Soft Part Sarcoma': "nan",
    'Diffuse Large B-cell Lymphoma Activated B-cell Type': "TCGA-DLBC",  
  
    'Ovary Epithelial Cancer': "TCGA-OV",
    'Renal Cell Carcinoma With MiT Translocations': ["TCGA-KIRC", "TCGA-KICH", "TCGA-KIRP"],  
  
    'Pancreatic Acinar Cell Adenocarcinoma': "nan",
    'Anaplastic Ependymoma': "nan",
    'B-cell Lymphoma': "TCGA-DLBC",
    'Congenital Mesoblastic Nephroma': "nan",
    'Cervical Sarcoma': "nan",
    'Poorly Differentiated Thyroid Carcinoma': "nan",
    'Central Nervous System Tumor With BCOR Internal Tandem Duplication': "nan",
    'Kidney Clear Cell Sarcoma': "nan",
    'Angiocentric Glioma': "nan",
    'Diffuse Large B-cell Lymphoma Germinal Center B-cell Type': "TCGA-DLBC",  
  
    'Renal Medullary Carcinoma': "nan",
    'Desmoplastic Small Round Cell Tumor': "nan",
    'Low Grade Glioma': "TCGA-LGG",
    'Polymorphous Low Grade Neuroepithelial Tumour Of The Young': "nan",
    'Pigmented Epithelioid Melanocytoma': "nan",
    'CNS Neuroblastoma With FOXR2 Activation': "nan",
    'Extramammary Paget Disease': "nan",
    'Peritoneal Carcinoma': "nan",
    'B-lymphoblastic Leukemia/lymphoma With TCF3-PBX1': "nan",
    'Isomorphic Diffuse Glioma': "nan",
    'Diffuse Astrocytoma, MYB- Or MYBL1-altered': "TCGA-LGG",  
  
    'Acute Myeloid Leukemia With Inv(16)(p13.1q22) Or T(16;16)(p13.1;q22)': "TCGA-LAML",
    'Acute Myeloid Leukemia With T(8;21); (q22; Q22.1)': "TCGA-LAML",
    'Acute Myeloid Leukemia With CBFA2T3::GLIS2 Fusion': "nan",
    'Supratentorial Ependymoma, YAP1 Fusion-positive': "nan",
    'Acute Myeloid Leukemia With BCR::ABL1 Fusion': "nan",
    'Sclerosing Epithelioid Fibrosarcoma': "nan",
    'Low-grade Fibromyxoid Sarcoma': "nan",
    'B-lymphoblastic Leukemia/lymphoma With BCR-ABL1': "nan",
    'Acute Myeloid Leukemia With MNX1::ETV6 Fusion': "nan",
    'AML With KAT6A::CREBBP Fusion': "nan",
    'B-lymphoblastic Leukemia/lymphoma With TCF3::HLF Fusion': "nan",
    'Acute Myeloid Leukemia With CEBPA Mutation': "TCGA-LAML",
    'B-lymphoblastic Leukemia With MEF2D Rearrangement': "nan",
    'B-lymphoblastic Leukemia With NUTM1 Rearrangement': "nan",
    'B-lymphoblastic Leukemia/lymphoma With IGH::IL3': "nan",
    'Large B-cell Lymphoma With IRF4 Rearrangement': "TCGA-DLBC",
    'Acute Myeloid Leukemia With RBM15::MRTFA Fusion': "nan"
}

ONCOKB_CANCER_TYPE_MAPPING_FOR_DIAGNOSTIC_ONLY = {
    'Early T-Cell Precursor Lymphoblastic Leukemia': None,  
    'Myelodysplastic Syndromes': None,  
    'T-Lymphoblastic Leukemia/Lymphoma': None,  
    'Diffuse Large B-Cell Lymphoma, NOS': 'TCGA-DLBC',  
    'Chronic Myelomonocytic Leukemia': None,  
    'Follicular Lymphoma': None,  
    'B-Lymphoblastic Leukemia/Lymphoma, BCR-ABL1 Like': None,  
    'Acute Myeloid Leukemia': 'TCGA-LAML',  
    'Juvenile Myelomonocytic Leukemia': None,  
    'MDS/MPN with Ring Sideroblasts and Thrombocytosis': None,  
    'Extranodal Marginal Zone Lymphoma of Mucosa-Associated Lymphoid Tissue (MALT lymphoma)': None,  
    'Angioimmunoblastic T-Cell Lymphoma': None,  
    'MDS with Ring Sideroblasts': None,  
    'Burkitt Lymphoma': None,  
    'Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma': None,  
    'Classical Hodgkin Lymphoma': None,  
    'Primary Mediastinal (Thymic) Large B-Cell Lymphoma': 'TCGA-DLBC',  
    'Primary Myelofibrosis': None,  
    'Myeloproliferative Neoplasms': None,  
    'Essential Thrombocythemia': None,  
    'AML with BCR-ABL1': 'TCGA-LAML',  
    'High-Grade B-Cell Lymphoma, with MYC and BCL2 and/or BCL6 Rearrangements': 'TCGA-DLBC',  
    'T-Cell Large Granular Lymphocytic Leukemia': None,  
    'Langerhans Cell Histiocytosis': None,  
    'Polycythemia Vera': None,  
    'Plasma Cell Myeloma': None,  
    'Atypical Chronic Myeloid Leukemia, BCR-ABL1-': None,  
    'T-Cell Prolymphocytic Leukemia': None,  
    'B-Lymphoblastic Leukemia/Lymphoma': None,  
    'Myeloid Sarcoma': 'TCGA-LAML',  
    'Splenic Marginal Zone Lymphoma': None,  
    'AML with t(8;21)(q22;q22.1);RUNX1-RUNX1T1': 'TCGA-LAML',  
    'Primary Cutaneous DLBCL, Leg Type': 'TCGA-DLBC',  
    'Anaplastic Large-Cell Lymphoma ALK Negative': None,  
    'Mixed Phenotype Acute Leukemia with t(9;22)(q34.1;q11.2); BCR-ABL1': 'TCGA-LAML',  
    'AML with Myelodysplasia-Related Changes': 'TCGA-LAML',  
    'Lymphoplasmacytic Lymphoma': None,  
    'Primary DLBCL of the central nervous system': 'TCGA-DLBC',  
    'Myeloid/Lymphoid Neoplasms with FGFR1 Rearrangement': None,  
    'AML with t(6;9)(p23;q34.1);DEK-NUP214': 'TCGA-LAML',  
    'Chronic Myeloid Leukemia, BCR-ABL1+': None,  
    'AML with Biallelic Mutations of CEBPA': 'TCGA-LAML',  
    'AML with inv(16)(p13.1q22) or t(16;16)(p13.1;q22);CBFB-MYH11': 'TCGA-LAML',  
    'Anaplastic Large-Cell Lymphoma ALK Positive': None,  
    'B-Lymphoblastic Leukemia/Lymphoma with t(5;14)(q31.1;q32.3) IL3-IGH': None,  
    'ALK Positive Large B-Cell Lymphoma': 'TCGA-DLBC',  
    'Therapy-Related Myeloid Neoplasms': 'TCGA-LAML',  
    'Erdheim-Chester Disease': None,  
    'APL with PML-RARA': 'TCGA-LAML',  
    'Systemic Mastocytosis': None,  
    'AML (megakaryoblastic) with t(1;22)(p13.3;q13.3);RBM15-MKL1': 'TCGA-LAML',  
    'B-Lymphoblastic Leukemia/Lymphoma with t(12;21)(p13.2;q22.1); ETV6-RUNX1': None,  
    'AML with Mutated RUNX1': 'TCGA-LAML',  
    'B-Lymphoblastic Leukemia/Lymphoma with t(1;19)(q23;p13.3);TCF3-PBX1': None,  
    'Myeloid/Lymphoid Neoplasms with PDGFRB Rearrangement': None,  
    'Myeloid/Lymphoid Neoplasms with PDGFRA Rearrangement': None,  
    'AML with Mutated NPM1': 'TCGA-LAML',  
    'Hairy Cell Leukemia': None,  
    'B-Lymphoblastic Leukemia/Lymphoma with t(9;22)(q34.1;q11.2);BCR-ABL1': None,  
    'AML with t(9;11)(p21.3;q23.3);MLLT3-KMT2A': 'TCGA-LAML',  
    'Mixed Phenotype Acute Leukemia with t(v;11q23.3); KMT2A Rearranged': 'TCGA-LAML',  
    'B-Lymphoblastic Leukemia/Lymphoma with t(v;11q23.3);KMT2A Rearranged': None,  
    'Mantle Cell Lymphoma': None,  
    'Myeloid/Lymphoid Neoplasms with PCM1-JAK2': None,  
    'Large B-Cell Lymphoma with IRF4 Rearrangement': 'TCGA-DLBC',  
    'Chronic Neutrophilic Leukemia': None,  
    'Myeloid Proliferations Related to Down Syndrome': 'TCGA-LAML',  
}



CGI_TUMOR_NAMES_MAPPING = {
    'Follicular lymphoma': np.nan,
    'Breast adenocarcinoma': ['TCGA-BRCA'],
    'Acute Myeloid Leukemia': ['TCGA-LAML'],
    'Acute lymphoblastic leukemia': np.nan,
    ' Chronic myeloid leukemia': np.nan,
    'Chronic myeloid leukemia': np.nan,
    'Waldenström macroglobulinemia': np.nan,
    'Medullary thyroid cancer': np.nan,
    'Non-Small Cell Lung Cancer': ['TCGA-LUAD', 'TCGA-LUSC'],
    'Stomach': ['TCGA-STAD'],
    'Ovary': ['TCGA-OV'],
    'Lung adenocarcinoma': ['TCGA-LUAD'],
    'Renal': ['TCGA-KIRC', 'TCGA-KIRP', 'TCGA-KICH'],
    'Bladder': ['TCGA-BLCA'],
    'Prostate adenocarcinoma': ['TCGA-PRAD'],
    'Colorectal cancer': ['TCGA-COAD', 'TCGA-READ'],
    'Colorectal adenocarcinoma': ['TCGA-COAD', 'TCGA-READ'],
    'Gastrointestinal stromal': np.nan,
    'Cholangiocarcinoma': ['TCGA-CHOL'],
    'Non-small cell lung': ['TCGA-LUAD', 'TCGA-LUSC'],
    'Any cancer type': ALL_TCGA_PROJ_IDS,
    'Gastroesophageal junction adenocarcinoma': ['TCGA-ESCA'],
    'Cutaneous melanoma': ['TCGA-SKCM'],
    'Head an neck squamous': ['TCGA-HNSC'],
    'Fibrous histiocytoma': np.nan,
    'Endometrium': ['TCGA-UCEC'],
    'Medulloblastoma': np.nan,
    'Inflammatory myofibroblastic': np.nan,
    'Hematologic malignancies': np.nan,
    'Lymphoma': np.nan,
    'Glioblastoma': ['TCGA-GBM'],
    'Thyroid carcinoma': ['TCGA-THCA'],
    'Glioma': ['TCGA-LGG', 'TCGA-GBM'],
    'Lung': ['TCGA-LUAD', 'TCGA-LUSC'],
    'Acute myeloid leukemia': ['TCGA-LAML'],
    'Myeloma': np.nan,
    'B cell lymphoma': np.nan,
    'Mesothelioma': ['TCGA-MESO'],
    'Thyroid': ['TCGA-THCA'],
    'Pancreas': ['TCGA-PAAD'],
    'Billiary tract': ['TCGA-CHOL'],
    'Malignant astrocytoma': ['TCGA-GBM'],
    'Pediatric glioma': np.nan,
    'Hairy-Cell leukemia': np.nan,
    'Lagerhans cell histiocytosis': np.nan,
    'Erdheim-Chester histiocytosis': np.nan,
    'NUT midline carcinoma': np.nan,
    'Myelodisplasic proliferative syndrome': np.nan,
    'Basal cell carcinoma': np.nan,
    'Chronic lymphocytic leukemia': np.nan,
    'Liposarcoma': ['TCGA-SARC'],
    'Atypical chronic myeloid leukemia': np.nan,
    'Lung squamous cell': ['TCGA-LUSC'],
    'Neuroblastoma': np.nan,
    'Head an neck': ['TCGA-HNSC'],
    'Rhabdomyosarcoma': np.nan,
    'Plexiform neurofibroma': np.nan,
    'Urinary tract carcinoma': ['TCGA-BLCA'],
    'Cervix squamous cell': ['TCGA-CESC'],
    'Cervix': ['TCGA-CESC'],
    'Myelofibrosis': np.nan,
    'Megakaryoblastic leukemia': ['TCGA-LAML'],
    'Adrenal adenoma': np.nan,
    'Systemic mastocytosis': np.nan,
    'Thymic': ['TCGA-THYM'],
    'Male germ cell tumor': ['TCGA-TGCT'],
    'Female germ cell tumor': np.nan,
    'Schwannoma': np.nan,
    'Malignant peripheral nerve sheat tumor': ['TCGA-SARC'],
    'Sarcoma': ['TCGA-SARC'],
    'Hepatic carcinoma': ['TCGA-LIHC'],
    'Mantle cell lymphoma': np.nan,
    'Myelodisplasic syndrome': np.nan,
    'Hyper eosinophilic advanced snydrome': np.nan,
    'Eosinophilic chronic leukemia': np.nan,
    'Angiosarcoma': np.nan,
    'Anaplastic oligodendroglioma': ['TCGA-LGG'],
    'Leukemia': np.nan,
    'Salivary glands': np.nan,
    'Neurofibroma': np.nan,
    'Acute Lymphoblastic Leukemia': np.nan,
    'Meningioma': np.nan,
    'Adenoid cystic carcinoma': np.nan,
    'Solid tumors': np.array(list(set(ALL_TCGA_PROJ_IDS)-set(NOT_SOLID_TUMOR))),
    'Dermatofibrosarcoma': np.nan,
    'Acute promyelocytic leukemia': None, 
    'Osteosarcoma': np.nan,
    'Retinoblastoma': np.nan,
    'Pancreas adenocarcinoma': ['TCGA-PAAD'],
    'Malignant rhabdoid tumor': np.nan,
    'Glioblastoma multiforme': ['TCGA-GBM'],
    'Renal angiomyolipoma': np.nan,
    'Giant cell astrocytoma': np.nan,
    'Lymphangioleiomyomatosis': np.nan,
}





CIVIC_MOLECULAR_PROFILE_MAPPING  = {
    "DNMT3A R882": "DNMT3A",
    "NRAS Q61": "NRAS",
    "MAP2K1 P124S": "MAP2K1",
    "MAP2K1 Q56P": "MAP2K1",
    "ARAF S214C": "ARAF",
    "NRAS G13D": "NRAS",
    "NRAS Q61L": "NRAS",
    "NRAS Q61R": "NRAS",
    "KIT D816V": "KIT",
    "NRAS Mutation": "NRAS",
    "BRAF V600": "BRAF",
    "ALK F1174L": "ALK",
    "KIT L576P": "KIT",
    "KRAS G12/G13": "KRAS",
    "KIT Exon 11 Mutation": "KIT",
    "FLT3 ITD": "FLT3",
    "BRAF V600E AND BRAF V600M": "BRAF",
    "BRAF V600E": "BRAF",
    "KRAS G12D": "KRAS",
    "BRAF V600D": "BRAF",
    "NPM1 EXON 11 MUTATION": "NPM1",
    "KRAS G12V": "KRAS",
    "PIK3CA Exon 21 Mutation": "PIK3CA",
    "WT1 Exon 7 Mutation": "WT1",
    "EML4::ALK Fusion AND ALK L1196M": "EML4;ALK",
    "FGFR3::BAIAP2L1 Fusion": "FGFR3;BAIAP2L1",
    "KRAS G13D": "KRAS",
    "NPM1 W288FS": "NPM1",
    "TSC1 Frameshift Truncation": "TSC1",
    "TSC1 Loss-of-function": "TSC1",
    "CEBPA Mutation": "CEBPA",
    "CEBPA N-TERMINAL FRAME SHIFT": "CEBPA",
    "FLT3 TKD MUTATION": "FLT3",
    "MGMT Promoter Methylation": "MGMT",
    "DNMT3A Mutation": "DNMT3A",
    "WT1 Exon 9 Mutation": "WT1",
    "BRCA1 Loss-of-function": "BRCA1",
    "BRCA2 Loss-of-function": "BRCA2",
    "CCND2 PROMOTER DEMETHYLATION": "CCND2",
    "CCND1 Overexpression": "CCND1",
    "IDH1 R132": "IDH1",
    "IDH1 R132C": "IDH1",
    "KRAS G12C": "KRAS",
    "EGFR L858R": "EGFR",
    "BCR::ABL1 Fusion": "BCR;ABL1",
    "EML4::ALK Fusion AND ALK C1156Y": "EML4;ALK",
    "EGFR T790M": "EGFR",
    "ERBB2 L755S": "ERBB2",
    "ESR1 L536Q": "ESR1",
    "ESR1 D538G": "ESR1",
    "ESR1 Y537C": "ESR1",
    "ESR1 Y537N": "ESR1",
    "ESR1 Y537S": "ESR1",
    "FLT3 ITD AND FLT3 D835Y": "FLT3",
    "KRAS Exon 2 Mutation": "KRAS",
    "KRAS G12A": "KRAS",
    "EML4::ALK Fusion": "EML4;ALK",
    "CDK4 EXPRESSION": "CDK4",
    "DDR2 G253C": "DDR2",
    "DDR2 G505S": "DDR2",
    "DDR2 G774V": "DDR2",
    "DDR2 I638F": "DDR2",
    "DDR2 L239R": "DDR2",
    "DDR2 L63V": "DDR2",
    "DDR2 S768R": "DDR2",
    "EGFR Exon 19 Deletion": "EGFR",
    "EGFR G719S": "EGFR",
    "ERBB2 D769H": "ERBB2",
    "ERBB2 D769Y": "ERBB2",
    "ERBB2 L755_T759del": "ERBB2",
    "ERBB2 G309A": "ERBB2",
    "ERBB2 L755W": "ERBB2",
    "ERBB2 P780INS": "ERBB2",
    "ERBB2 R678Q": "ERBB2",
    "ERBB2 R896C": "ERBB2",
    "ERBB2 V777L": "ERBB2",
    "ERBB2 V842I": "ERBB2",
    "FGFR2::OGA Fusion": "FGFR2;OGA",
    "FGFR2::TACC3 Fusion": "FGFR2;TACC3",
    "GATA2 EXPRESSION": "GATA2",
    "PIK3CA E542K": "PIK3CA",
    "PIK3CA H1047R": "PIK3CA",
    "PTEN R233*": "PTEN",
    "TP53 R175H": "TP53",
    "IDH2 R140": "IDH2",
    "CCND1 Amplification": "CCND1",
    "CCND1 Expression": "CCND1",
    "CCND2 OVEREXPRESSION": "CCND2",
    "CCNE1 Overexpression": "CCNE1",
    "CDKN2A Promoter Hypermethylation": "CDKN2A",
    "IDH2 R172K": "IDH2",
    "KRAS G12": "KRAS",
    "NOTCH1 D1642H": "NOTCH1",
    "NOTCH1 R2327W": "NOTCH1",
    "NOTCH1 S2275FS": "NOTCH1",
    "NOTCH1 V2444FS": "NOTCH1",
    "PIK3CA E545K": "PIK3CA",
    "TP53 R248Q": "TP53",
    "TP53 R248W": "TP53",
    "TP53 R249": "TP53",
    "TP53 R273C": "TP53",
    "TP53 R273H": "TP53",
    "BCL2 reg_e@[IGH]::BCL2": "BCL2",
    "FOXP1 AMPLIFICATION": "FOXP1",
    "REL AMPLIFICATION": "REL",
    "RUNX1 Mutation": "RUNX1",
    "IGF2 Overexpression": "IGF2",
    "AURKA EXPRESSION": "AURKA",
    "VHL Mutation": "VHL",
    "TET2 Mutation": "TET2",
    "PBRM1 Mutation": "PBRM1",
    "BCL2 Overexpression": "BCL2",
    "VHL Loss-of-function": "VHL",
    "EZH2 Y646": "EZH2",
    "AKT1 Q79K": "AKT1",
    "EML4::ALK Fusion AND ALK Amplification": "EML4;ALK",
    "EML4::ALK Fusion AND ALK G1202R": "EML4;ALK",
    "EML4::ALK Fusion AND ALK S1206Y": "EML4;ALK",
    "EML4::ALK Fusion AND ALK T1151dup": "EML4;ALK",
    "APC Mutation": "APC",
    "AR F877L": "AR",
    "AR W742": "AR",
    "ASXL1 Mutation": "ASXL1",
    "ATM Mutation": "ATM",
    "AURKA Overexpression": "AURKA",
    "BAP1 EXPRESSION": "BAP1",
    "BAP1 Mutation": "BAP1",
    "AKAP9::BRAF Fusion": "AKAP9;BRAF",
    "BRCA1 Mutation": "BRCA1",
    "BRCA2 Mutation": "BRCA2",
    "CCNE1 Amplification": "CCNE1",
    "EGFR Amplification": "EGFR",
    "EGFR Copy Number Variation": "EGFR",
    "EGFR Overexpression": "EGFR",
    "TMPRSS2::ERG Fusion": "TMPRSS2;ERG",
    "FGFR3 Y373C": "FGFR3",
    "IDH2 R172": "IDH2",
    "NCOA3 AMPLIFICATION": "NCOA3",
    "NCOA3 OVEREXPRESSION": "NCOA3",
    "PGR Expression": "PGR",
    "PIK3CA Amplification": "PIK3CA",
    "PTEN Deletion": "PTEN",
    "PTEN Loss": "PTEN",
    "SMAD4 Mutation": "SMAD4",
    "SMARCA4 INACTIVATING MUTATION": "SMARCA4",
    "TERT Amplification": "TERT",
    "TERT Promoter Mutation": "TERT",
    "TP53 Deleterious Mutation": "TP53",
    "TP53 Mutation": "TP53",
    "TP53 Truncating Mutation": "TP53",
    "ERBB2 Amplification": "ERBB2",
    "CDK12 Loss-of-function": "CDK12",
    "TP53 DNA Binding Domain Mutation": "TP53",
    "ATM S2289*": "ATM",
    "ATM N2875H": "ATM",
    "TERT C228T": "TERT",
    "XRCC1 R194W": "XRCC1",
    "GSTP1 Deletion": "GSTP1",
    "BIRC7 Amplification": "BIRC7",
    "EGFR Exon 4 Deletion": "EGFR",
    "KRAS RS61764370": "KRAS",
    "KIT rs17084733": "KIT",
    "EZH2 Intron 6 Mutation": "EZH2",
    "MTHFR A222V": "MTHFR",
    "GSTP1 I105V": "GSTP1",
    "ABCG2 Q141K": "ABCG2",
    "XRCC1 Q399R": "XRCC1",
    "ABCB1 S893T": "ABCB1",
    "ABCB1 I1145I": "ABCB1",
    "ERCC2 K751Q": "ERCC2",
    "TYMS 5' TANDEM REPEAT": "TYMS",
    "LRP1B EXON 12-22 DELETION": "LRP1B",
    "FGFR1 Amplification": "FGFR1",
    "FGFR1 Expression": "FGFR1",
    "v::ROS1 Fusion": "ROS1",
    "MET Amplification": "MET",
    "ATR I774FS": "ATR",
    "CDKN2A p16 Expression": "CDKN2A",
    "KIF5B::RET Fusion": "KIF5B;RET",
    "HRAS G13D": "HRAS",
    "CD274 Expression": "CD274",
    "MTOR Mutation": "MTOR",
    "AKT2 EXPRESSION": "AKT2",
    "AKT1 E17K": "AKT1",
    "MTOR H1968Y": "MTOR",
    "NF2 K159fs": "NF2",
    "EGFR S492R": "EGFR",
    "FBXW7 Mutation": "FBXW7",
    "SMAD4 Underexpression": "SMAD4",
    "MTOR P2213S": "MTOR",
    "AGK::BRAF Fusion": "AGK;BRAF",
    "PAPSS1::BRAF Fusion": "PAPSS1;BRAF",
    "TRIM24::BRAF Fusion": "TRIM24;BRAF",
    "BRAF L597R": "BRAF",
    "ERBB3 Overexpression": "ERBB3",
    "NT5E Overexpression": "NT5E",
    "MYD88 Overexpression": "MYD88",
    "RET Overexpression": "RET",
    "RIT1 OVEREXPRESSION": "RIT1",
    "RIT1 Mutation": "RIT1",
    "STK11 EXON 1-2 MUTATION": "STK11",
    "STK11 Underexpression": "STK11",
    "SYK OVEREXPRESSION": "SYK",
    "EML4::ALK Fusion AND ALK L1152R": "EML4;ALK",
    "EML4::ALK Fusion AND ALK G1269A": "EML4;ALK",
    "ERBB4 Mutation": "ERBB4",
    "PIK3CA Mutation": "PIK3CA",
    "EGFR VIII": "EGFR",
    "EGFR Amplification AND EGFR EGFRVIII": "EGFR",
    "PTEN Expression": "PTEN",
    "NRG1 Expression": "NRG1",
    "AREG Expression": "AREG",
    "TGFA EXPRESSION": "TGFA",
    "EGFR G724S": "EGFR",
    "EREG EXPRESSION": "EREG",
    "MAPK1 E322K": "MAPK1",
    "MAPK1 Amplification": "MAPK1",
    "KRAS A146V": "KRAS",
    "MET Mutation": "MET",
    "MET Exon 14 Skipping Mutation": "MET",
    "FGFR3 Overexpression": "FGFR3",
    "PTPRD Mutation": "PTPRD",
    "DEFA1 EXPRESSION": "DEFA1",
    "ERCC1 Expression": "ERCC1",
    "NOTCH1 Amplification": "NOTCH1",
    "WEE1 RS3910384": "WEE1",
    "FNTB RS11623866": "FNTB",
    "PTPRT Promoter Hypermethylation": "PTPRT",
    "VEGFA Decreased Peri-therapeutic Expression": "VEGFA",
    "DNMT1 EXPRESSION": "DNMT1",
    "KRAS Mutation": "KRAS",
    "PDCD4 EXPRESSION": "PDCD4",
    "MGMT RS16906252": "MGMT",
    "TFF3 EXPRESSION": "TFF3",
    "DKK1 NUCLEAR EXPRESSION": "DKK1",
    "EGF EXPRESSION": "EGF",
    "MDM2 EXPRESSION": "MDM2",
    "HMOX1 EXPRESSION": "HMOX1",
    "SPHK1 OVEREXPRESSION": "SPHK1",
    "TYMS Overexpression": "TYMS",
    "PBK OVEREXPRESSION": "PBK",
    "SMARCA4 Underexpression": "SMARCA4",
    "CDKN1A EXPRESSION": "CDKN1A",
    "ALCAM EXPRESSION": "ALCAM",
    "STMN1 EXPRESSION": "STMN1",
    "RSF1 Amplification": "RSF1",
    "AR OVEREXPRESSION": "AR",
    "CDKN1B CYTOPLASMIC MISLOCALIZATION": "CDKN1B",
    "AR V7 EXPRESSION": "AR",
    "ERBB3 EXPRESSION": "ERBB3",
    "UGT1A EXPRESSION": "UGT1A",
    "ERBB4 NUCLEAR TRANSLOCATION": "ERBB4",
    "ERBB4 EXPRESSION": "ERBB4",
    "SLFN11 EXPRESSION": "SLFN11",
    "RAC1 P29S": "RAC1",
    "BIRC5 NUCLEAR EXPRESSION": "BIRC5",
    "TP53 Wildtype": "TP53",
    "MRE11 Loss": "MRE11",
    "ATM Underexpression": "ATM",
    "TOP1 Amplification": "TOP1",
    "CDKN1B EXPRESSION": "CDKN1B",
    "AGR2 EXPRESSION": "AGR2",
    "EGFR Exon 18 Overexpression": "EGFR",
    "TIMP1 Overexpression": "TIMP1",
    "PTP4A3 OVEREXPRESSION": "PTP4A3",
    "TYMS Amplification": "TYMS",
    "IGF1R EXPRESSION": "IGF1R",
    "EPHB4 EXPRESSION": "EPHB4",
    "TYMS Underexpression": "TYMS",
    "TOP2A EXPRESSION": "TOP2A",
    "TOP1 EXPRESSION": "TOP1",
    "HSPA5 EXPRESSION": "HSPA5",
    "EIF4EBP1 PHOSPHORYLATION": "EIF4EBP1",
    "TUBB3 EXPRESSION": "TUBB3",
    "EGFR Y1092 PHOSPHORYLATION": "EGFR",
    "IGF1R NUCLEAR EXPRESSION": "IGF1R",
    "CFLAR EXPRESSION": "CFLAR",
    "PROM1 EXPRESSION": "PROM1",
    "FOXP3 EXPRESSION": "FOXP3",
    "RPS6 PHOSPHORYLATION": "RPS6",
    "JAK1 OVEREXPRESSION": "JAK1",
    "BRCA1 Expression": "BRCA1",
    "HSPB1 EXPRESSION": "HSPB1",
    "NQO1 EXPRESSION": "NQO1",
    "NQO1 P187S": "NQO1",
    "BRCA1 Underexpression": "BRCA1",
    "ABCB1 Overexpression": "ABCB1",
    "v::ALK Fusion": "ALK",
    "CXCR4 EXPRESSION": "CXCR4",
    "MAGEH1 EXPRESSION": "MAGEH1",
    "ABCC3 Amplification": "ABCC3",
    "ABCC10 Overexpression": "ABCC10",
    "ASNS Amplification": "ASNS",
    "CDX2 EXPRESSION": "CDX2",
    "POU5F1 EXPRESSION": "POU5F1",
    "ERBB2 Kinase Domain Mutation": "ERBB2",
    "ERBB2 Y772_A775DUP": "ERBB2",
    "EGFR C797S": "EGFR",
    "ERBB2 SERUM LEVELS": "ERBB2",
    "THBS2 UNDEREXPRESSION": "THBS2",
    "LMNA::NTRK1 Fusion OR TPM3::NTRK1 Fusion": "LMNA;TPM3;NTRK1",
    "IDH1 R132H": "IDH1",
    "TERT RS2736100": "TERT",
    "STAG2 Underexpression": "STAG2",
    "HLA-DRA EXPRESSION": "HLA-DRA",
    "MRE11 Frameshift": "MRE11",
    "v::NTRK1 Fusion": "NTRK1",
    "KIT EXPRESSION": "KIT",
    "CBFB::MYH11 Fusion": "CBFB;MYH11",
    "KMT2A::MLLT3 Fusion": "KMT2A;MLLT3",
    "HIF1A 3' UTR Polymorphism": "HIF1A",
    "HIF1A OVEREXPRESSION": "HIF1A",
    "VHL Loss": "VHL",
    "FLT3 D835": "FLT3",
    "PSMB8 NUCLEAR EXPRESSION": "PSMB8",
    "PBK NUCLEAR EXPRESSION": "PBK",
    "EGFR G465R": "EGFR",
    "NEDD9 EXPRESSION": "NEDD9",
    "ETS2 RS461155": "ETS2",
    "KRT18 UNDEREXPRESSION": "KRT18",
    "FGF13 CYTOPLASMIC EXPRESSION": "FGF13",
    "SS18::SSX1 Fusion": "SS18;SSX1",
    "SS18::SSX2 Fusion": "SS18;SSX2",
    "SS18::SSX4 Fusion": "SS18;SSX4",
    "ABCB1 S893A/T": "ABCB1",
    "EGFR R451C": "EGFR",
    "EGFR K467T": "EGFR",
    "FCGR2B I232T": "FCGR2B",
    "MET Amplification AND MET Splice Site (c.3028G>A)": "MET",
    "ROS1 G2032R AND CD74::ROS1 Fusion": "ROS1;CD74",
    "TSC2 Q1178*": "TSC2",
    "MTOR F2108L": "MTOR",
    "RAD51D R186*": "RAD51D",
    "ALDH1A2 Overexpression": "ALDH1A2",
    "ALDH1A2 Underexpression": "ALDH1A2",
    "CIP2A EXPRESSION": "CIP2A",
    "CIP2A Underexpression": "CIP2A",
    "MIR218-1 EXPRESSION": "MIR218-1",
    "BRCA1 P968FS": "BRCA1",
    "KRAS Q22*": "KRAS",
    "DDX43 Overexpression": "DDX43",
    "KIT RS3733542": "KIT",
    "TBK1 Overexpression": "TBK1",
    "STK11 Loss": "STK11",
    "TP53 Loss": "TP53",
    "HAVCR2 Overexpression": "HAVCR2",
    "MMP2 SERUM LEVELS": "MMP2",
    "MMP9 SERUM LEVELS": "MMP9",
    "ACTA1 EXPRESSION": "ACTA1",
    "HSPH1 NUCLEAR EXPRESSION": "HSPH1",
    "HSPH1 T17 DELETION": "HSPH1",
    "PIM1 NUCLEAR EXPRESSION": "PIM1",
    "MDM2 SNP309": "MDM2",
    "ERBB2 L866M": "ERBB2",
    "ERBB2 S310F/Y": "ERBB2",
    "MIR218-1 UNDEREXPRESSION": "MIR218-1",
    "EML4::ALK e20::e20": "EML4;ALK",
    "KDR R961W": "KDR",
    "EML4::ALK e6::e20": "EML4;ALK",
    "GNAQ Mutation": "GNAQ",
    "GNA11 Mutation": "GNA11",
    "PMS2 K706FS*19": "PMS2",
    "KIT Mutation": "KIT",
    "GNAQ Q209": "GNAQ",
    "FGFR2 Mutation": "FGFR2",
    "ALK Mutation": "ALK",
    "CD72::ROS1 Fusion": "CD72;ROS1",
    "ROS1 G2032R AND v::ROS1 Fusion": "ROS1",
    "ROS1 L2026M AND CD74::ROS1 Fusion": "ROS1;CD74",
    "ROS1 L2155S AND CD74::ROS1 Fusion": "ROS1;CD74",
    "ROS1 G2101A AND CD74::ROS1 Fusion": "ROS1;CD74",
    "CLTC::ALK Fusion": "CLTC;ALK",
    "B4GALT1 Overexpression": "B4GALT1",
    "BCL2L11 Deletion Polymorphism": "BCL2L11",
    "ALK I1171": "ALK",
    "EML4::ALK Fusion AND ALK V1180L": "EML4;ALK",
    "SIRT1 Overexpression": "SIRT1",
    "KRAS G12R": "KRAS",
    "PALB2 Biallelic Inactivation": "PALB2",
    "SMAD4 Expression": "SMAD4",
    "FANCC Loss-of-function": "FANCC",
    "RB1 EXPRESSION": "RB1",
    "MLH1 METHYLATION": "MLH1",
    "PTPN11 Overexpression": "PTPN11",
    "FLT3 T227M": "FLT3",
    "PALB2 L531FS*30": "PALB2",
    "MTOR S2215Y": "MTOR",
    "MTOR E1799K": "MTOR",
    "FGFR2 N550K": "FGFR2",
    "RB1 Overexpression": "RB1",
    "PPP1R15A RS557806": "PPP1R15A",
    "EML4::ALK Fusion AND ALK F1245C": "EML4;ALK",
    "ALK G1269A AND v::ALK Fusion": "ALK",
    "ALK G1202R AND v::ALK Fusion": "ALK",
    "CDK4 Amplification": "CDK4",
    "CDKN2A Loss": "CDKN2A",
    "CDKN2B Loss": "CDKN2B",
    "CDK4 R24C": "CDK4",
    "ASXL1 EXON 12 MUTATION": "ASXL1",
    "EGFR S768I": "EGFR",
    "BRAF V600K": "BRAF",
    "SMAD4 LOSS": "SMAD4",
    "SF3B1 K700E": "SF3B1",
    "SF3B1 K666N": "SF3B1",
    "MAP2K7 E116K": "MAP2K7",
    "MTOR E2014K AND MTOR E2419K": "MTOR",
    "RICTOR Amplification": "RICTOR",
    "BIRC5 Overexpression": "BIRC5",
    "BRAF L597S": "BRAF",
    "BRAF L597Q": "BRAF",
    "BRAF K601E": "BRAF",
    "BRAF L597V": "BRAF",
    "PTEN Mutation": "PTEN",
    "NF1 Mutation": "NF1",
    "NRAS Q61K": "NRAS",
    "ALK I1171N AND HIP1::ALK Fusion": "ALK;HIP1",
    "EML4::ALK Fusion AND ALK I1171S": "EML4;ALK",
    "RAF1 Amplification": "RAF1",
    "KRAS Amplification": "KRAS",
    "CEBPA BIALLELIC INACTIVATION": "CEBPA",
    "SRSF2 MUTATION": "SRSF2",
    "NRAS G12/G13": "NRAS",
    "AR Mutation": "AR",
    "NOTCH1 Loss-of-function": "NOTCH1",
    "CDK6 Overexpression": "CDK6",
    "GNAQ Q209P": "GNAQ",
    "PTEN V317FS": "PTEN",
    "RB1 Loss-of-function": "RB1",
    "ESR1 Overexpression": "ESR1",
    "MTOR M2327I": "MTOR",
    "MTOR A2034V": "MTOR",
    "BRAF D594G": "BRAF",
    "FLT3 D835H": "FLT3",
    "FLT3 D835H/Y": "FLT3",
    "JAK1 Q503*": "JAK1",
    "JAK2 c.1641+1dup": "JAK2",
    "B2M S14FS": "B2M",
    "PPFIBP2::BRAF Fusion": "PPFIBP2;BRAF",
    "KIAA1549::BRAF Fusion": "KIAA1549;BRAF",
    "EGFR Expression": "EGFR",
    "MET Overexpression": "MET",
    "MKI67 EXPRESSION": "MKI67",
    "RAD23B EXPRESSION": "RAD23B",
    "CCDC6::RET Fusion": "CCDC6;RET",
    "MAP2K1 C121S": "MAP2K1",
    "FGFR3 S249C": "FGFR3",
    "FGFR2 Amplification": "FGFR2",
    "FGF3 Amplification": "FGF3",
    "RB1 PHOSPHORYLATION": "RB1",
    "PIK3R1 Mutation": "PIK3R1",
    "STK11 D194E": "STK11",
    "AKT2 Amplification": "AKT2",
    "PTEN R130*": "PTEN",
    "RB1 M695FS*26": "RB1",
    "JUN Overexpression": "JUN",
    "FOS Overexpression": "FOS",
    "CDKN2A RS3814960": "CDKN2A",
    "MDM2 RS34886328": "MDM2",
    "CBLB RS2305035": "CBLB",
    "PRDM1 MUTATION": "PRDM1",
    "IDH1 Mutation": "IDH1",
    "IDH2 Mutation": "IDH2",
    "SMAD4 Deletion": "SMAD4",
    "LRP1B DELETION": "LRP1B",
    "ATRX Underexpression": "ATRX",
    "MET D1228N": "MET",
    "AXL EXPRESSION": "AXL",
    "GAS6 EXPRESSION": "GAS6",
    "ETV4 Overexpression": "ETV4",
    "STAG3 Underexpression": "STAG3",
    "MAP2K1 Q56_V60del": "MAP2K1",
    "BRAF::CUL1 Fusion": "BRAF;CUL1",
    "ZKSCAN1::BRAF Fusion": "ZKSCAN1;BRAF",
    "BRAF L505H": "BRAF",
    "BRCA2 D3095E": "BRCA2",
    "MLH1 EXPRESSION": "MLH1",
    "BCOR Mutation": "BCOR",
    "SDC4::ROS1 Fusion": "SDC4;ROS1",
    "ERBB2 Mutation": "ERBB2",
    "EGFR Mutation": "EGFR",
    "BRAF Mutation": "BRAF",
    "HGF EXPRESSION": "HGF",
    "SOX10 Loss": "SOX10",
    "FGF2 EXPRESSION": "FGF2",
    "EIF1AX MUTATION": "EIF1AX",
    "ERRFI1 E384*": "ERRFI1",
    "ESR1 S463P": "ESR1",
    "SGK1 Overexpression": "SGK1",
    "BRAF G596C": "BRAF",
    "SMARCB1 Underexpression": "SMARCB1",
    "NF2 Loss": "NF2",
    "SH2B3 RS3184504": "SH2B3",
    "KIF23 EXPRESSION": "KIF23",
    "ERBB3 V104M": "ERBB3",
    "ERBB3 R103G": "ERBB3",
    "ERBB3 G284R": "ERBB3",
    "GADD45A rs681673": "GADD45A",
    "BRCA2 TRUNCATING MUTATION": "BRCA2",
    "BRCA1 Alu insertion": "BRCA1",
    "HOXB13 G84E": "HOXB13",
    "KLLN PROMOTER METHYLATION": "KLLN",
    "EGFR D761Y": "EGFR",
    "PDGFRA Amplification": "PDGFRA",
    "EWSR1::DDIT3 Fusion": "EWSR1;DDIT3",
    "EGFR G719": "EGFR",
    "EGFR S720": "EGFR",
    "FUS::DDIT3 Fusion": "FUS;DDIT3",
    "EGFR K757R": "EGFR",
    "EGFR E746G": "EGFR",
    "MLH1 E13fs": "MLH1",
    "MSH2 R383*": "MSH2",
    "MLH1 V534R": "MLH1",
    "MLH1 G606FS*2": "MLH1",
    "MLH1 c.790+1G>A": "MLH1",
    "MLH1 K618DEL": "MLH1",
    "MLH1 P138T": "MLH1",
    "MLH1 R687FS": "MLH1",
    "EGFR V769_D770insASV": "EGFR",
    "MLH1 R100*": "MLH1",
    "MLH1 T117M": "MLH1",
    "MLH1 Q426FS": "MLH1",
    "MLH1 V49A": "MLH1",
    "EGFR Exon 20 Insertion": "EGFR",
    "MLH1 D667FS": "MLH1",
    "MLH1 M1L": "MLH1",
    "MLH1 R265G": "MLH1",
    "MLH1 V213FS": "MLH1",
    "MLH1 N551T": "MLH1",
    "MLH1 A424T": "MLH1",
    "MLH1 Q149*": "MLH1",
    "MLH1 R226*": "MLH1",
    "MLH1 P536FS": "MLH1",
    "MLH1 G67R": "MLH1",
    "MLH1 I68S": "MLH1",
    "MLH1 G65D": "MLH1",
    "MLH1 A681V": "MLH1",
    "MSH6 P138T": "MSH6",
    "MSH2 V273FS": "MSH2",
    "MSH2 E28FS": "MSH2",
    "VHL E55FS (c.163_164delGA)": "VHL",
    "MSH6 I891FS": "MSH6",
    "MSH6 R1242H": "MSH6",
    "PMS2 R315*": "PMS2",
    "MLH1 M490T": "MLH1",
    "MSH2 K172*": "MSH2",
    "MSH2 E483G": "MSH2",
    "MSH6 V352I": "MSH6",
    "MSH6 R1242C": "MSH6",
    "ERBB3 V855A": "ERBB3",
    "FGFR2::BICC1 Fusion": "FGFR2;BICC1",
    "FGFR2::AHCYL1 Fusion": "FGFR2;AHCYL1",
    "CHEK2 1100DELC": "CHEK2",
    "CHEK2 I157T": "CHEK2",
    "RRM1 Overexpression": "RRM1",
    "RRM2 OVEREXPRESSION": "RRM2",
    "POLE Mutation": "POLE",
    "MET D1228V": "MET",
    "SQSTM1::NTRK1 Fusion": "SQSTM1;NTRK1",
    "RUNX1 K83E": "RUNX1",
    "RUNX1 Y260*": "RUNX1",
    "RUNX1 R135FSX177": "RUNX1",
    "RUNX1 D198Y": "RUNX1",
    "RUNX1 A107P": "RUNX1",
    "MSH2 Loss": "MSH2",
    "MSH6 LOSS": "MSH6",
    "RUNX1 T148HFSX9": "RUNX1",
    "ERBB2 G776L": "ERBB2",
    "ERBB2 G778_P780DUP": "ERBB2",
    "ERBB2 M774DELINSWLV": "ERBB2",
    "HLA-C COPY-NEUTRAL LOSS OF HETEROZYGOSITY": "HLA-C",
    "JAK1 S703I": "JAK1",
    "ARAF S490T": "ARAF",
    "GNAS R201C": "GNAS",
    "FGFR3 Mutation": "FGFR3",
    "FGFR2::v Fusion OR FGFR2::? Fusion": "FGFR2",
    "VHL M54IFS (c.162_166delGGAGG)": "VHL",
    "AKT3 Overexpression": "AKT3",
    "ALK Alternative Transcript (ATI)": "ALK",
    "VHL M1FS (c.1_17del17)": "VHL",
    "VHL M1? (c.1-1_20del21)": "VHL",
    "VHL M1? (c.3G>A)": "VHL",
    "VHL N7D (c.19A>G)": "VHL",
    "VHL Y98FS (c.291_310del20)": "VHL",
    "PDGFRA P577S": "PDGFRA",
    "PDGFRA R841K": "PDGFRA",
    "PDGFRA H845Y": "PDGFRA",
    "PDGFRA G853D": "PDGFRA",
    "MTAP Underexpression": "MTAP",
    "VPS37A Underexpression": "VPS37A",
    "ERBB2 Overexpression": "ERBB2",
    "GNAS c.393T>C": "GNAS",
    "NRAS G12D": "NRAS",
    "PIK3CA Rare Mutation": "PIK3CA",
    "PIK3CA C420R": "PIK3CA",
    "PIK3CA K111N": "PIK3CA",
    "PIK3CA H1047L": "PIK3CA",
    "EGFR L858R OR EGFR Exon 19 Deletion": "EGFR",
    "NRAS G13R": "NRAS",
    "KRAS A146T": "KRAS",
    "KRAS A146P": "KRAS",
    "KRAS G12S": "KRAS",
    "TP53 R273L": "TP53",
    "TP53 Y220C": "TP53",
    "EGFR G719A": "EGFR",
    "EGFR Wildtype": "EGFR",
    "EGFR E746_A750del": "EGFR",
    "TP53 Overexpression": "TP53",
    "TP53 Y234C": "TP53",
    "TP53 ALTERATION": "TP53",
    "TP53 R282L": "TP53",
    "TP53 R213P": "TP53",
    "BRCA1 Q1467*": "BRCA1",
    "BRCA2 M1R": "BRCA2",
    "BRCA2 M1I": "BRCA2",
    "BRCA2 V159M": "BRCA2",
    "BRCA2 V211L": "BRCA2",
    "BRCA2 V211I": "BRCA2",
    "BRCA2 R2336P": "BRCA2",
    "KIT D820Y": "KIT",
    "MGMT Underexpression": "MGMT",
    "RRM1 Underexpression": "RRM1",
    "BRAF Amplification": "BRAF",
    "ROS1 G2032R": "ROS1",
    "MAP2K1 K57N": "MAP2K1",
    "LMNA::NTRK1 Fusion": "LMNA;NTRK1",
    "LMNA::NTRK1 Fusion AND NTRK1 G595R AND NTRK1 G667C": "LMNA;NTRK1",
    "DCC EXPRESSION": "DCC",
    "VHL W8* (c.24G>A)": "VHL",
    "CTNNB1 Activating Mutation": "CTNNB1",
    "MERTK OVEREXPRESSION": "MERTK",
    "TP53 CONSERVED DOMAIN MUT": "TP53",
    "FLT3 D835V": "FLT3",
    "BRAF Non-V600": "BRAF",
    "PIK3CA H1047R OR PIK3CA H1047L": "PIK3CA",
    "NRAS Q61H": "NRAS",
    "PIK3CA E545G": "PIK3CA",
    "EGFR L861Q": "EGFR",
    "NRAS G12C": "NRAS",
    "PIK3CA G1049R": "PIK3CA",
    "KRAS Q61H": "KRAS",
    "KRAS Q61L": "KRAS",
    "KRAS Q61R": "KRAS",
    "KRAS Q61K": "KRAS",
    "KRAS Q61": "KRAS",
    "PIK3CA N345K": "PIK3CA",
    "KIT K642E": "KIT",
    "EGFR R108K": "EGFR",
    "EGFR T263P": "EGFR",
    "EGFR A289V": "EGFR",
    "EGFR V742A": "EGFR",
    "EGFR E746_T751>I": "EGFR",
    "EGFR G719D": "EGFR",
    "EGFR V774A": "EGFR",
    "EGFR V834I": "EGFR",
    "EGFR L838P": "EGFR",
    "EGFR L747_P753delinsS": "EGFR",
    "EGFR D770_N771insSVD": "EGFR",
    "EGFR H773_V774insH": "EGFR",
    "EGFR L861": "EGFR",
    "PIK3CA S158L": "PIK3CA",
    "PIK3CA R93W": "PIK3CA",
    "EGFR R776C": "EGFR",
    "ARID1A Q456*": "ARID1A",
    "EGFR H773_V774insNPH": "EGFR",
    "EGFR D770_N771insGL": "EGFR",
    "EGFR A864T": "EGFR",
    "EGFR N826S": "EGFR",
    "EGFR A763_Y764insFQEA": "EGFR",
    "AKT3 E17K": "AKT3",
    "EGFR D770_N771insGT": "EGFR",
    "EGFR A767_V769dupASV": "EGFR",
    "EGFR L747_S752delinsQ": "EGFR",
    "EGFR L861R": "EGFR",
    "EGFR Rare Exon 18-21 Mutation": "EGFR",
    "POLD1 C284Y": "POLD1",
    "POLD1 E374K": "POLD1",
    "PIK3R2 N561D": "PIK3R2",
    "PIK3CA D350G": "PIK3CA",
    "NRAS Q179X": "NRAS",
    "ABL1 R351W": "ABL1",
    "ABL1 G340L": "ABL1",
    "EGFR M766_A767insAI": "EGFR",
    "EGFR Y764_V765insHH": "EGFR",
    "EGFR D770delinsGY": "EGFR",
    "EGFR P772_H773insYNP": "EGFR",
    "JAK2 Splice Site (c.1641+2T>G)": "JAK2",
    "ACVR1 Gain-of-Function": "ACVR1",
    "v::RET Fusion": "RET",
    "FGFR3::TACC3 Fusion AND FGFR2::CCDC6 Fusion": "FGFR3;TACC3;FGFR2;CCDC6",
    "TP53 M237I": "TP53",
    "EGFR Gain-of-function": "EGFR",
    "POLE P286R": "POLE",
    "POLE V411L": "POLE",
    "POLE S459F": "POLE",
    "VHL N78H (c.232A>C)": "VHL",
    "FLT3 Mutation": "FLT3",
    "PIK3CA Exon 21 Mutation AND PIK3CA Exon 10 Mutation": "PIK3CA",
    "VHL S183* (c.548C>A)": "VHL",
    "VHL S80N (c.239G>A)": "VHL",
    "VHL Splice Site (c.463+1G>C)": "VHL",
    "VHL R161* (c.481C>T)": "VHL",
    "ARID1A Underexpression": "ARID1A",
    "VHL Splice Site (c.341-2A>C)": "VHL",
    "SLC3A2::NRG1 Fusion": "SLC3A2;NRG1",
    "ATP1B1::NRG1 Fusion": "ATP1B1;NRG1",
    "SDC4::NRG1 Fusion": "SDC4;NRG1",
    "EGFR::RAD51 Fusion": "EGFR;RAD51",
    "BAP1 ALTERNATIVE TRANSCRIPT (ATI)": "BAP1",
    "STRN::ALK Fusion": "STRN;ALK",
    "BARD1 Loss-of-function": "BARD1",
    "CUX1::BRAF Fusion": "CUX1;BRAF",
    "ASS1 Loss": "ASS1",
    "RASA1 Loss-of-function": "RASA1",
    "TLK2 Amplification": "TLK2",
    "BRAF G469E": "BRAF",
    "VHL L184P (c.551T>C)": "VHL",
    "VHL A56_P59del (c.166_178del)": "VHL",
    "STRN::NTRK2 Fusion": "STRN;NTRK2",
    "TPM3::NTRK1 Fusion": "TPM3;NTRK1",
    "PDE4DIP::NTRK1 Fusion": "PDE4DIP;NTRK1",
    "VHL G144E (c.431G>A)": "VHL",
    "VHL Splice Region (c.463+8C>T)": "VHL",
    "VHL S65L (c.194C>T)": "VHL",
    "EGFR Rare Mutation": "EGFR",
    "PIK3CA Exon 10 Mutation": "PIK3CA",
    "BRAF Amplification AND ( BRAF V600E OR BRAF V600K )": "BRAF",
    "PREX2 R172I": "PREX2",
    "v::NRG1 Fusion": "NRG1",
    "KRAS G13V": "KRAS",
    "ETV6::NTRK2 Fusion": "ETV6;NTRK2",
    "BRAF intron 10 rearrangement": "BRAF",
    "BRAF intron 9 rearrangement": "BRAF",
    "BRAF D594K": "BRAF",
    "FGFR3::TACC3 Fusion": "FGFR3;TACC3",
    "STK11 Mutation": "STK11",
    "SDHB p.193_196dupSTSC (c.577_588dupAGCACCAGCTGC)": "SDHB",
    "ETV6::NTRK3 Fusion": "ETV6;NTRK3",
    "KMT2C Loss": "KMT2C",
    "VHL L118P (c.353T>C)": "VHL",
    "VHL D121_A122del (c.361_366del)": "VHL",
    "VHL P138R (c.413C>G)": "VHL",
    "VHL N150fs (c.447del)": "VHL",
    "VHL Q164* (c.490C>T)": "VHL",
    "BRAF V600E AND EZH2 Y646F": "BRAF;EZH2",
    "SMARCA4 Loss": "SMARCA4",
    "PIK3CA Exon 21 Mutation OR PIK3CA Exon 10 Mutation": "PIK3CA",
    "FGFR2 Mutation OR FGFR2::v Fusion OR FGFR2::? Fusion": "FGFR2",
    "PIK3CA Q546E OR PIK3CA Q546R": "PIK3CA",
    "PIK3CA H1047R OR PIK3CA H1047Y OR PIK3CA H1047L": "PIK3CA",
    "FIP1L1::PDGFRA Fusion": "FIP1L1;PDGFRA",
    "KIT N822K": "KIT",
    "FGFR1OP2::FGFR1 Fusion": "FGFR1OP2;FGFR1",
    "NFE2L2 Mutation": "NFE2L2",
    "PIK3CA E545K OR PIK3CA E545A OR PIK3CA E545G OR PIK3CA E545D": "PIK3CA",
    "CAD::ALK Fusion": "CAD;ALK",
    "GOPC::ROS1 Fusion": "GOPC;ROS1",
    "APP::NRG1 Fusion": "APP;NRG1",
    "MET R1004G": "MET",
    "ROS1 G2032R AND SLC4A4::ROS1 Fusion": "ROS1;SLC4A4",
    "BRAF G466V": "BRAF",
    "H3-3A K28M": "H3-3A",
    "BRAF V600_K601>E": "BRAF",
    "BRAF G469": "BRAF",
    "FGF19 Overexpression": "FGF19",
    "BRCA2 K3326*": "BRCA2",
    "BRAF N486_P490del": "BRAF",
    "NRF1::BRAF Fusion": "NRF1;BRAF",
    "CDKN2A c.151-1G>C": "CDKN2A",
    "DPYD EXON 11-19 DELETION": "DPYD",
    "MET::ATXN7L1 Fusion": "MET;ATXN7L1",
    "FGFR2 P253R": "FGFR2",
    "LPP::HMGA2 Fusion OR HMGA2::LPP Fusion": "LPP;HMGA2",
    "PIK3CA V955I": "PIK3CA",
    "FLT3 D835Y": "FLT3",
    "FLT3 Y842C": "FLT3",
    "FLT3 F691L": "FLT3",
    "FLT3 D835I": "FLT3",
    "GOLGA4::RAF1 Fusion": "GOLGA4;RAF1",
    "PALB2 Mutation": "PALB2",
    "ATRX Mutation": "ATRX",
    "ANO10::RAF1 Fusion": "ANO10;RAF1",
    "EGFR N771_P772insL": "EGFR",
    "EGFR D770_N771insG": "EGFR",
    "EGFR S768_D770dup": "EGFR",
    "KRAS G10_A11insG": "KRAS",
    "KRAS A11_G12insGA": "KRAS",
    "KDR R1032Q": "KDR",
    "EZH2 Y646H": "EZH2",
    "CD44 CD44v6": "CD44",
    "H3C2 K27M": "H3C2",
    "NTRK1 G595R AND NTRK1 G667S": "NTRK1",
    "HRAS Mutation": "HRAS",
    "NUP98::NSD1 Fusion": "NUP98;NSD1",
    "PIM1 L2V": "PIM1",
    "PIM1 P81S": "PIM1",
    "PIM1 S97N": "PIM1",
    "PIK3CA K944N": "PIK3CA",
    "PIK3CA F930S": "PIK3CA",
    "PIK3CA V955G": "PIK3CA",
    "PIK3CA K966E": "PIK3CA",
    "FLCN c.1285dupC": "FLCN",
    "IGF1R Overexpression": "IGF1R",
    "ERBB2 Exon 20 Insertion": "ERBB2",
    "ERCC1 Underexpression": "ERCC1",
    "SLC29A1 Overexpression": "SLC29A1",
    "v::TFE3 Fusion": "TFE3",
    "QKI::RAF1 Fusion": "QKI;RAF1",
    "KANK1::NTRK2 Fusion": "KANK1;NTRK2",
    "MS4A1 Mutation": "MS4A1",
    "EML4::NTRK3 Fusion": "EML4;NTRK3",
    "SCP2::NTRK1 Fusion": "SCP2;NTRK1",
    "EGFR Amplification AND EGFR::SEPTIN14 Fusion": "EGFR;SEPTIN14",
    "KIF5B::EGFR Fusion": "KIF5B;EGFR",
    "EZH2 expression": "EZH2",
    "EML4::ALK Fusion AND ALK I1171N AND ALK L1196M": "EML4;ALK",
    "EML4::ALK Fusion AND ALK G1202R AND ALK I1171N AND ALK L1196M": "EML4;ALK",
    "EGFR S645C": "EGFR",
    "EGFR K754E": "EGFR",
    "ARAF S214F": "ARAF",
    "CDK12 Mutation": "CDK12",
    "CHEK2 mutation": "CHEK2",
    "RAD54L Mutation": "RAD54L",
    "BRIP1 Mutation": "BRIP1",
    "BARD1 Mutation": "BARD1",
    "CHEK1 Mutation": "CHEK1",
    "RAD51B Mutation": "RAD51B",
    "RAD51D Mutation": "RAD51D",
    "EGFR S768I OR EGFR G719A OR EGFR L861Q": "EGFR",
    "BRCA1 Mutation OR BRCA2 Mutation": "BRCA1;BRCA2",
    "QKI::NTRK2 Fusion": "QKI;NTRK2",
    "ESR1 Mutation": "ESR1",
    "IDH1 R132C OR IDH1 R132H OR IDH1 R132L OR IDH1 R132G OR IDH1 R132S": "IDH1",
    "IDH2 R172K OR IDH2 R172G OR IDH2 R172W": "IDH2",
    "NTRK3 G623R AND EML4::NTRK3 Fusion": "NTRK3;EML4",
    "ASPSCR1::TFE3 Fusion": "ASPSCR1;TFE3",
    "v::TFEB Fusion": "TFEB",
    "BCOR ITD": "BCOR",
    "RB1 Wildtype AND ( CDKN2A Loss OR CDKN2A Mutation )": "RB1;CDKN2A",
    "BRAF V600E OR BRAF K601E": "BRAF",
    "ERBB2 S310F": "ERBB2",
    "v::MITF Fusion": "MITF",
    "TPR::NTRK1 Fusion": "TPR;NTRK1",
    "IDH2 Mutation OR IDH1 Mutation": "IDH2;IDH1",
    "ERBB2 L755A": "ERBB2",
    "ERBB2 L755M": "ERBB2",
    "ERBB2 L755P": "ERBB2",
    "ERBB2 A775_G776insTVMA": "ERBB2",
    "ERBB2 A775_G776insV": "ERBB2",
    "ERBB2 A775_G776insVVMA": "ERBB2",
    "ERBB2 G776_V777delinsVCD": "ERBB2",
    "ERBB2 G776delinsCV": "ERBB2",
    "ERBB2 G776delinsLC": "ERBB2",
    "ERBB2 G776delinsVC": "ERBB2",
    "ERBB2 G778_P780dup": "ERBB2",
    "ERBB2 G778_S779insLPS": "ERBB2",
    "MYB Rearrangement": "MYB",
    "MYBL1 Rearrangement": "MYBL1",
    "RUNX1::RUNX1T1 Fusion": "RUNX1;RUNX1T1",
    "PIK3CA Mutation OR PTEN Mutation OR AKT1 Mutation": "PIK3CA;PTEN;AKT1",
    "PIK3CA R88Q": "PIK3CA",
    "BCR::NTRK2 Fusion": "BCR;NTRK2",
    "Kataegis Positive": '',
    "PIK3CA Mutation OR RB1 Mutation OR ESR1 Mutation": "PIK3CA;RB1;ESR1",
    "NTRK1 Amplification": "NTRK1",
    "IFNGR1 Loss": "IFNGR1",
    "v::IRF4 Fusion": "IRF4",
    'ARID1A Loss OR ARID1A Wildtype': 'ARID1A',
    'NF2 Y177fs': 'NF2',
    'VHL V170G (c.509T>G)': 'VHL',
    'RET C609Y': 'RET',
    'VHL L129Q (c.386insAGA)': 'VHL',
    'CASP8 Overexpression': 'CASP8',
    'VHL E55= (c.165G>A)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 M343T': 'ABL1;BCR',  
    'FCGR2A H167R': 'FCGR2A',
    'PRPS1 S103T': 'PRPS1',
    'VHL W88* (c.263G>A)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 L248R': 'ABL1;BCR',  
    'VHL Y175* (c.525C>G)': 'VHL',
    "VHL 3'UTR alteration (c.*70C>A)": 'VHL',
    'VHL R113FS (c.337delC)': 'VHL',
    'YAP1::MAMLD1 Fusion': 'MAMLD1;YAP1',  
    'TP53 S241F': 'TP53',
    'TP53 D281E': 'TP53',
    'BRAF K483M': 'BRAF',
    'NUP153::ABL1 Fusion': 'ABL1;NUP153',  
    'BCR::ABL1 Fusion AND ABL1 D363G': 'ABL1;BCR',  
    'CTCF K365T': 'CTCF',
    'VHL P154= (c.462A>C)': 'VHL',
    'VHL C162fs (c.483del)': 'VHL',
    'CHEK2 R474C c.1420C>T': 'CHEK2',
    'VHL P59fs (c.173_174insC)': 'VHL',
    'RANBP2::ABL1 Fusion': 'ABL1;RANBP2',  
    'BCR::ABL1 Fusion AND ABL1 P480A': 'ABL1;BCR',
    'STAT3 SH2 DOMAIN MUTATION': 'STAT3',
    'VHL S68W (c.203C>G)': 'VHL',
    'IKZF1 Deletion': 'IKZF1',
    'BRAF A728V': 'BRAF',
    'VHL F91* (c.272_273delinsAA)': 'VHL',
    'SNX2::ABL1 Fusion': 'ABL1;SNX2',
    'TP53 P151S': 'TP53',
    'NOTCH1 P2514FS': 'NOTCH1',
    'VHL R108dup (c.322_324dup)': 'VHL',
    'RAF1 R391W': 'RAF1',
    'KIT Y503_F504insAY': 'KIT',
    'EGFR G598V': 'EGFR',
    'SMARCA2 K755R': 'SMARCA2',
    'VHL R176fs (c.526del)': 'VHL',
    'TP53 A276V': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 F359I': 'ABL1;BCR',
    'ATM c.7089+1del': 'ATM',
    'TP53 L344P': 'TP53',
    'VHL R79P (c.236G>C)': 'VHL',
    'AKT1 Overexpression': 'AKT1',
    'VHL D143fs (c.430delG)': 'VHL',
    'EGFR T847I': 'EGFR',
    'VHL E186K (c.556G>A)': 'VHL',
    'VHL M54fs (c.161dup)': 'VHL',
    'VHL P40fs (c.118ins)': 'VHL',
    'TP53 P152L': 'TP53',
    'TP53 R181H': 'TP53',
    'VHL W88S (c.263G>C)': 'VHL',
    'LRP1B Loss-of-function': 'LRP1B',
    'PDGFRA D842I': 'PDGFRA',
    'CTNNB1 T41A': 'CTNNB1',
    'FGFR3 K650N': 'FGFR3',
    'VHL L116V (c.346C>G)': 'VHL',
    'PAX3::FOXO1 Fusion': 'FOXO1;PAX3',
    'v::PDGFRA Fusion': 'PDGFRA',  
    'VHL C162W (c.486C>G)': 'VHL',
    'VHL V84M (c.250G>A)': 'VHL',
    'VHL Null (Partial deletion of Exons 2 & 3)': 'VHL',
    'TP53 R337P': 'TP53',
    'VHL E52K (c.154G>A)': 'VHL',
    'DUX4::v Fusion': 'DUX4',  
    'CTAG1B Overexpression': 'CTAG1B',
    'KIT D820A': 'KIT',
    'VHL R167L (c.500G>T)': 'VHL',
    'EGFR V441F': 'EGFR',
    'ATM A2062V': 'ATM',
    'ABL1 Double Ph': 'ABL1',  
    'VHL T202fs (c.606insA)': 'VHL',
    'EZH2 Mutation': 'EZH2',
    'VHL Y156C (c.467A>G)': 'VHL',
    'KIT A502_Y503insAY': 'KIT',
    'VHL L153fs (c.457delC)': 'VHL',
    'LMNA::NTRK1 Fusion AND NTRK1 G595R': 'LMNA;NTRK1',
    'BCR::ABL1 Fusion AND ABL1 F311L': 'ABL1;BCR',
    'NOT KIT D816V': '',  
    'DPYD DPYD*13 HOMOZYGOSITY': 'DPYD',
    'TFG::ROS1 Fusion': 'ROS1;TFG',
    'MNX1::ETV6 Fusion': 'ETV6;MNX1',
    'EGFR P772_V774insPHV': 'EGFR',
    'YWHAE::NUTM2A Fusion OR YWHAE::NUTM2B Fusion OR YWHAE::NUTM2E Fusion': 'NUTM2A;NUTM2B;NUTM2E;YWHAE',  
    'KIT T417_D419delinsY': 'KIT',
    'BCR::ABL1 Fusion AND ABL1 L364I': 'ABL1;BCR',
    'PAX5::JAK2 Fusion': 'JAK2;PAX5',
    'PDGFRA D842Y': 'PDGFRA',
    'CSF3R Mutation': 'CSF3R',
    'BCR::JAK2 Fusion': 'BCR;JAK2',
    'v::NTRK3 Fusion': 'NTRK3',
    'PTCH1 Mutation': 'PTCH1',
    'VHL R177fs (c.528del)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 E459K': 'ABL1;BCR',
    'VHL Q164R (c.491A>G)': 'VHL',
    'VHL R167Q (c.500G>A)': 'VHL',
    'ETV6::NTRK3 Fusion AND NTRK3 G623R': 'ETV6;NTRK3',
    'MYCL EXPRESSION': 'MYCL',
    'KIT T670I': 'KIT',
    'TP53 T230S': 'TP53',
    'ERBB2 Mutation OR ERBB3 Mutation': 'ERBB2;ERBB3',
    'NTRK3::SCAPER Fusion': 'NTRK3;SCAPER',
    'VHL Splice Site (c.463+2T>C)': 'VHL',
    'VHL L169P (c.506T>C)': 'VHL',
    'YAP1::v Fusion': 'YAP1',
    'TP53 R156H': 'TP53',
    'VHL S111C (c.331A>T)': 'VHL',
    'BCL2 G101V': 'BCL2',
    'VHL D197FS (c.589delG)': 'VHL',
    'VHL 3p26.3-25.3 11Mb del': 'VHL',
    'TP53 R280K': 'TP53',
    'VHL S68P (c.202T>C)': 'VHL',
    'VHL E55fs (c.163delG)': 'VHL',
    'EGFR Y801H': 'EGFR',
    'VHL L184R (c.551T>G)': 'VHL',
    'EGFR R705K': 'EGFR',
    'KDR D717V': 'KDR',
    'YAP1::TFE3 Fusion': 'TFE3;YAP1',
    'FGFR3 V555M': 'FGFR3',
    'TP53 R156P': 'TP53',
    'VHL A149T (c.445G>A)': 'VHL',
    'JAK2 F694L': 'JAK2',
    'KIT K550_K558del': 'KIT',
    'TP53 F270S': 'TP53',
    'VHL D92G (c.275A>G)': 'VHL',
    'NFE2L2 G31A': 'NFE2L2',
    'LMNA::NTRK1 Fusion AND NTRK1 G667C': 'LMNA;NTRK1',
    'VHL P59fs (c.176delC)': 'VHL',
    'BRAF N581S': 'BRAF',
    'VHL Splice Region (c.340+5G>C)': 'VHL',
    'VHL Y112H (c.334T>C)': 'VHL',
    'ARID1A Loss': 'ARID1A',
    'PTTG1 OVEREXPRESSION': 'PTTG1',
    'UGT1A1 UGT1A1*28': 'UGT1A1',
    'RET V804M': 'RET',
    'VHL Q96* (c.286C>T)': 'VHL',
    'ABL1 C475V': 'ABL1',
    'PTPRB Loss-of-function': 'PTPRB',
    'DICER1 E1705K': 'DICER1',
    'ETV6::JAK2 Fusion': 'ETV6;JAK2',
    'VHL P86R (c.257C>G)': 'VHL',
    'SRSF2 P95H': 'SRSF2',
    'DICER1 D1709N': 'DICER1',
    'VHL E55* (c.163G>T)': 'VHL',
    'TNKS2::PDGFRA Fusion': 'PDGFRA;TNKS2',
    'WWTR1::CAMTA1 Fusion': 'CAMTA1;WWTR1',
    'LMNA::NTRK1 Fusion AND NTRK1 F589L': 'LMNA;NTRK1',
    'KIT Internal Duplication': 'KIT',
    'VHL V170D (c.509T>A)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 F359V': 'ABL1;BCR',
    'PIK3CA P471L': 'PIK3CA',
    'VHL E55RfsTer11 (c.163delG)': 'VHL',
    'VHL R161P (c.482G>C)': 'VHL',
    'VHL Y175C (c.524A>G)': 'VHL',
    'U2AF1 MUTATION': 'U2AF1',
    'VHL L188fs (c.562delC)': 'VHL',
    'VHL Y185* (c.555C>G)': 'VHL',
    'VHL T152fs (c.455insA)': 'VHL',
    'VHL P146fs (c.437del)': 'VHL',
    'DNAJB1::PRKACA Fusion': 'DNAJB1;PRKACA',
    'TBL1XR1::CSF1R Fusion': 'CSF1R;TBL1XR1',
    'ABL1 Non-P-Loop Mutation': 'ABL1',
    'VHL G104A (c.311G>C)': 'VHL',
    'VHL Deletion': 'VHL',
    'NOTCH1 Mutation': 'NOTCH1',
    'KMT2C MUTATION': 'KMT2C',
    'VHL *214W (c.642A>G)': 'VHL',
    'VHL H191FS (c.571delC)': 'VHL',
    'EZH2 Y646S': 'EZH2',
    'KRAS G13': 'KRAS',
    'CTLA4::CD28 Fusion': 'CD28;CTLA4',
    'VHL L178P (c.533T>C)': 'VHL',
    'MYOD1 L122R': 'MYOD1',
    'PRPS1 V53A': 'PRPS1',
    'VHL Intronic deletion (c.341-13delCGTTTCCAACAATTTCTCGGTGT)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 M351T': 'ABL1;BCR',
    'VHL Y156D (c.466T>G)': 'VHL',
    'KIT V560G': 'KIT',
    'VHL Q195* (c.583C>T)': 'VHL',
    'VHL V166D (c.497T>A)': 'VHL',
    'TP53 Y163N': 'TP53',
    'ZNF274::JAK2 Fusion': 'JAK2;ZNF274',
    'BCR::ABL1 Fusion AND ABL1 V289I': 'ABL1;BCR',
    'TP53 C135W': 'TP53',
    'CALR Mutation': 'CALR',
    'GNA11 R183C': 'GNA11',
    'BCR::ABL1 Fusion AND ABL1 Y253F': 'ABL1;BCR',
    'PML::RARA Fusion AND PML A216V': 'PML;RARA',
    'VHL R200W (c.598C>T)': 'VHL',
    'ALK F1245C': 'ALK',
    'NTRK3 F617L': 'NTRK3',
    'VHL I180V (c.538A>G)': 'VHL',
    'PRPS1 L191F': 'PRPS1',
    'TP53 P152T': 'TP53',
    'FGFR3 A391E': 'FGFR3',
    'v::RET Fusion OR RET Mutation': 'RET',
    'VHL Y175N (c.523T>A)': 'VHL',
    'VHL C77fs (c.228dup)': 'VHL',
    'VHL *214L (c.641G>T)': 'VHL',
    'SSTR5 expression': 'SSTR5',
    'ZFTA::RELA Fusion': 'RELA;ZFTA',
    'VHL N131S (c.392A>G)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 M244V': 'ABL1;BCR',
    'ATF7IP::JAK2 Fusion': 'ATF7IP;JAK2',
    'EGFR L838V': 'EGFR',
    'PARP1 OVEREXPRESSION': 'PARP1',
    'BCL2 F104I': 'BCL2',
    'VHL E189fs (c.565del)': 'VHL',
    'VHL G93C (c.277G>T)': 'VHL',
    'PRPS1 N144S': 'PRPS1',
    'PDGFRA V561A': 'PDGFRA',
    'CIC::DUX4 Fusion': 'CIC;DUX4',
    'BCR::ABL1 Fusion AND ABL1 L384M': 'ABL1;BCR',
    'PPFIBP1::JAK2 Fusion': 'PPFIBP1;JAK2',
    'BCR::ABL1 Fusion AND ABL1 Y253H': 'ABL1;BCR',
    'VHL L188R (c.563T>G)': 'VHL',
    'TP53 I162F': 'TP53',
    'VHL V166A (c.497T>C)': 'VHL',
    'MYB AMPLIFICATION': 'MYB',
    'DICER1 E1813Q': 'DICER1',
    'VHL P86fs (c.254_255insC)': 'VHL',
    'EGFR D770_N771insNPG': 'EGFR',
    'PDGFRA D842V': 'PDGFRA',
    'VHL R120G (c.358A>G)': 'VHL',
    'PIK3CA E545Q': 'PIK3CA',
    'SMO Mutation': 'SMO',
    'TP53 D281N': 'TP53',
    'KIT K484_G487DEL': 'KIT',
    'VHL R167W (c.499C>T)': 'VHL',
    'VHL L135fs (c.404del)': 'VHL',
    'RET M918T': 'RET',
    'VHL V84L (c.250G>T)': 'VHL',
    'VHL Null (Large deletion)': 'VHL',
    'TP53 C242Y': 'TP53',
    'VHL c.128-?_250+?': 'VHL',  
    'BCR::ABL1 Fusion AND ABL1 L364P': 'ABL1;BCR',
    'v::PDGFRB Fusion': 'PDGFRB',
    'CTNNB1 S45P': 'CTNNB1',
    'CTAG2 Overexpression': 'CTAG2',
    'VHL V66Gfs*89 (c.197_209del)': 'VHL',
    'NT5C2 Mutation': 'NT5C2',
    'FCGR3A F212V': 'FCGR3A',
    'SRSF2 P95L': 'SRSF2',
    'VHL H115Y (c.343C>T)': 'VHL',
    'TP53 A161T': 'TP53',
    'TP53 S241T': 'TP53',
    'PDGFRA Mutation': 'PDGFRA',
    'v::ALK Fusion OR v::ROS1 Fusion': 'ALK;ROS1',
    'BCR::ABL1 Fusion AND ABL1 E255K AND ABL1 V299L': 'ABL1;BCR',
    'CBL Y371H': 'CBL',
    'NRAS G12': 'NRAS',
    'NT5C2 K359Q': 'NT5C2',
    'VHL Y112* (c.336C>A)': 'VHL',
    'VHL R177* (c.529A>T)': 'VHL',
    'VHL R107H (c.320G>A)': 'VHL',
    'MEF2D::CSF1R Fusion': 'CSF1R;MEF2D',
    'VHL L129P (c.386T>C)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 E255V': 'ABL1;BCR',
    'CALR EXON 9 FRAMESHIFT': 'CALR',
    'VHL Q132P (c.395A>C)': 'VHL',
    'EZH2 Overexpression': 'EZH2',
    'VHL A149S (c.445G>T)': 'VHL',
    'FLT3 Overexpression': 'FLT3',
    'LYN OVEREXPRESSION': 'LYN',
    'KRAS R164Q': 'KRAS',
    'PTEN C136R': 'PTEN',
    'BCR::PDGFRA Fusion': 'BCR;PDGFRA',
    'MYCN Amplification': 'MYCN',
    'BCR::ABL1 Fusion AND ABL1 E292L': 'ABL1;BCR',
    'VHL S111C (c.330_331delinsTT)': 'VHL',
    'VHL Exon 1-3 Deletion': 'VHL',
    'VHL L140fs (c.417_418delTC)': 'VHL',
    'PRPS1 T303S': 'PRPS1',
    'VHL Y98FS (c.291delC)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 F317S': 'ABL1;BCR',
    'EWSR1::FLI1 Fusion': 'EWSR1;FLI1',
    'VHL R161= (c.481C>A)': 'VHL',
    'TP53 Y220H': 'TP53',
    'TP53 L252F': 'TP53',
    'VHL L101G (c.301_302delinsGG)': 'VHL',
    'ATM D1930V': 'ATM',
    'BCR::ABL1 Fusion AND ABL1 D421G': 'ABL1;BCR',
    'KIT D820G': 'KIT',
    'BCR::ABL1 Fusion AND ABL1 E279K': 'ABL1;BCR',
    'VHL S80R (c.238A>C)': 'VHL',
    'CDKN1A rs1801270': 'CDKN1A',
    'VHL P154L (c.461C>T)': 'VHL',
    'VHL R167fs (c.502insTTGTCCGT)': 'VHL',
    'PCM1::JAK2 Fusion': 'JAK2;PCM1',
    'ATM R3008C': 'ATM',
    'TP53 C124R': 'TP53',
    'ATM K293*': 'ATM',
    'VHL K159fs (c.473dup)': 'VHL',
    'PRKCB D427N': 'PRKCB',
    'PRPS1 C77S': 'PRPS1',
    'KIT N822H': 'KIT',
    'VHL P138T (c.412C>A)': 'VHL',
    'RCSD1::ABL1 Fusion': 'ABL1;RCSD1',
    'VHL P154fs (c.462delA)': 'VHL',
    'DPYD DPYD*2A HOMOZYGOSITY': 'DPYD',
    'FGFR2::v Fusion': 'FGFR2',
    'MYC Overexpression': 'MYC',
    'SLCO1B1 RS4149056': 'SLCO1B1',
    'EBF1::JAK2 Fusion': 'EBF1;JAK2',
    'KDR A1065T': 'KDR',
    'VHL Exon 3 Deletion': 'VHL',
    'FGFR3 K650L': 'FGFR3',
    'VHL Q73fs (c.214insGCCC)': 'VHL',
    'ERBB2 T862A': 'ERBB2',
    'ABL1 TKD Mutation': 'ABL1',
    'VHL G123fs (c.369_375delGACACAC)': 'VHL',
    'VHL C162Y (c.485G>A)': 'VHL',
    'ZMIZ1::ABL1 Fusion': 'ABL1;ZMIZ1',
    'BCR::ABL1 Fusion AND ABL1 N336S': 'ABL1;BCR',
    'VHL P71fs (c.211insT)': 'VHL',
    'CDKN2B METHYLATION': 'CDKN2B',
    'ATM T2666A': 'ATM',
    'ACVR1 G356D': 'ACVR1',
    'PTCH1 LOH': 'PTCH1',
    'AGGF1::PDGFRB Fusion AND PDGFRB C843G': 'AGGF1;PDGFRB',
    'SMARCA2 R1159Q': 'SMARCA2',
    'TP53 R342P': 'TP53',
    'NT5C2 R238W': 'NT5C2',
    'BCR::ABL1 Fusion AND ABL1 M388L': 'ABL1;BCR',
    'TP53 R181G': 'TP53',
    'FGFR3 K650T': 'FGFR3',
    'ATM D1682H': 'ATM',
    'TP53 K139E': 'TP53',
    'VHL W117C (c.351G>T)': 'VHL',
    'VHL V155L (c.463G>C)': 'VHL',
    'VHL W88R (c.262T>C)': 'VHL',
    'VHL R79_S80del (c.236_241delGCAGTC)': 'VHL',
    'BRAF Wildtype': 'BRAF',
    'UGT1A1 UGT1A1*60': 'UGT1A1',
    'PAX7::FOXO1 Fusion': 'FOXO1;PAX7',
    'TP53 G245S': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 L387F': 'ABL1;BCR',
    'VHL R161G (c.481C>G)': 'VHL',
    'TP53 G266E': 'TP53',
    'VHL A56fs (c.166dup)': 'VHL',
    'EGFR L747P': 'EGFR',
    'VHL F119L (c.357C>G)': 'VHL',
    'KIT M541L': 'KIT',
    'CDH1 MUTATION': 'CDH1',
    'ALK F1245V': 'ALK',
    'BCR::ABL1 Fusion AND ABL1 H396R': 'ABL1;BCR',
    'EML4::ALK Fusion AND ALK L1198F AND ALK C1156Y': 'ALK;EML4',
    'VHL A56fs (c.166_167insA)': 'VHL',
    'VHL V74G (c.221T>G)': 'VHL',
    'BTK C481S': 'BTK',
    'KIT V555_V559DEL': 'KIT',
    'DDX41 R164W': 'DDX41',
    'TP53 L139N': 'TP53',
    'CDKN2A Deletion': 'CDKN2A',
    'VHL R69fs (c.204insG)': 'VHL',
    'VHL L163H (c.488T>A)': 'VHL',
    'JAK2 V617F': 'JAK2',
    'VHL 106insR (c.316insGCC)': 'VHL',
    'BRAF V600E OR NRAS Mutation OR HRAS Mutation OR KRAS Mutation OR NF1 Mutation': 'BRAF;HRAS;KRAS;NF1;NRAS',
    'BRCA1 W1815X': 'BRCA1',
    'FGFR3 G370C': 'FGFR3',
    'PRPS1 I72V': 'PRPS1',
    'BCR::ABL1 Fusion AND ABL1 E355G': 'ABL1;BCR',
    'SETBP1 G870S': 'SETBP1',
    'VHL N78I (c.233A>T)': 'VHL',
    'VHL F76del (c.227_229del)': 'VHL',
    'PRKAA2 T172 PHOSPHORYLATION': 'PRKAA2',
    'KIT C809G': 'KIT',
    'VHL P86A (c.256C>G)': 'VHL',
    'VHL K159fs (c.477_478insCA)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 E98G': 'ABL1;BCR',
    'PIK3R2 G373R': 'PIK3R2',
    'VHL H115P (c.344A>C)': 'VHL',
    'KIT K558_V559del': 'KIT',
    'PDGFRA I843DEL': 'PDGFRA',
    'VHL F148* (c.443_455delinsA)': 'VHL',
    'NF1 Mutation OR GNA11 Q209L': 'GNA11;NF1',
    'VHL Rearrangement': 'VHL',
    'FGFR3 K650E': 'FGFR3',
    'RHOA MUTATION': 'RHOA',
    'NTRK3 Amplification': 'NTRK3',
    'KAT6A::CREBBP Fusion': 'CREBBP;KAT6A',
    'VHL A122I (c.364_365GC>AT)': 'VHL',
    'ABL1 L298V': 'ABL1',
    'TP53 H179R': 'TP53',
    'VHL E160fs (c.477del)': 'VHL',
    'EWSR1::FLI1 e7::e6': 'EWSR1;FLI1',
    'ALK Exon 4-11 Deletion': 'ALK',
    'GNAS R201': 'GNAS',
    'ARAF V145L': 'ARAF',
    'PML B2 DOMAIN MUTATION': 'PML',
    'SFPQ::ABL1 Fusion': 'ABL1;SFPQ',
    'KIT Exon 13 Mutation': 'KIT',
    'IL6 Overexpression': 'IL6',
    'TP53 H179Y': 'TP53',
    'EGFR N842S': 'EGFR',
    'BCR::ABL1 Fusion AND ABL1 L248V': 'ABL1;BCR',
    'VHL G93_Y98del (c.275_292del)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 E450V': 'ABL1;BCR',
    'BCR::ABL1 Fusion AND ABL1 S438C': 'ABL1;BCR',
    'TP53 L330R': 'TP53',
    'EGFR M766_A767insASV': 'EGFR',
    'MEN1 FRAMESHIFT TRUNCATION': 'MEN1',
    'VHL A149fs (c.449del14-nt)': 'VHL',
    'ATM F2732V': 'ATM',
    'VHL E46* (c.136G>T)': 'VHL',
    'TP53 G245D': 'TP53',
    'VHL I151F (c.451A>T)': 'VHL',
    'EGFR N826Y': 'EGFR',
    'STAG2 MUTATION': 'STAG2',
    'VHL S65P (c.193T>C)': 'VHL',
    'VHL Exon 2 Deletion': 'VHL',
    'VHL S65FS (c.194delC)': 'VHL',
    'CDKN2A Loss OR CDKN2A Mutation': 'CDKN2A',
    'USP25::JAK2 Fusion': 'JAK2;USP25',
    'EZH2 Activating Mutation': 'EZH2',
    'VHL V87fs (c.255_256insC)': 'VHL',
    'RET C634W': 'RET',
    'CSF3R T618I': 'CSF3R',
    'VHL F136S (c.407T>C)': 'VHL',
    'EBF1::PDGFRB Fusion': 'EBF1;PDGFRB',
    'PTPRD V253I': 'PTPRD',
    'TP53 Y236S': 'TP53',
    'VHL W88fs (c.261dup)': 'VHL',
    'FGFR3 R248C': 'FGFR3',
    'ERBB2 H878Y': 'ERBB2',
    "VHL 3'UTR alteration (c.639+10C>G)": 'VHL',
    'GON4L::NTRK1 Fusion': 'GON4L;NTRK1',
    'BCR::ABL1 Fusion AND ABL1 L387M': 'ABL1;BCR',
    'VHL W88* (c.264G>A)': 'VHL',
    'VHL G114C (c.340G>T)': 'VHL',
    'VHL P81S (c.241C>T) and L188V (c.562C>G)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 G398R': 'ABL1;BCR',
    'VHL N150S (c.449A>G)': 'VHL',
    'VHL I151M (c.453C>G)': 'VHL',
    'TTF1 AMPLIFICATION': 'TTF1',
    'TP53 R158H': 'TP53',
    'EWSR1::ERG Fusion': 'EWSR1;ERG',
    'TP53 P47S': 'TP53',
    'FOXR2 Rearrangement': 'FOXR2',
    'TPR::JAK2 Fusion': 'JAK2;TPR',
    'VHL G144fs (c.429_439del)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 F311I': 'ABL1;BCR',
    'BCR::ABL1 Fusion AND ABL1 Q252H': 'ABL1;BCR',
    'PIK3CA I391M': 'PIK3CA',
    'KLF5 E419K': 'KLF5',
    'BCR::ABL1 Fusion AND ABL1 V379I': 'ABL1;BCR',
    'ALK R1275Q': 'ALK',
    'TP53 P72R': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 F317R': 'ABL1;BCR',
    'MEF2D::v Fusion': 'MEF2D',
    'PRPS1 PRPS1 MUTATION': 'PRPS1',
    'PAX8::PPARG Fusion': 'PAX8;PPARG',
    'VHL R107G (c.319C>G)': 'VHL',
    'PPP2R2A Mutation': 'PPP2R2A',
    'IGH::IL3 Fusion': 'IL3;IGH',
    'VHL G104= (c.312C>G)': 'VHL',
    'PDGFRA D842_H845DELDIMH': 'PDGFRA',
    'VHL H115fs (c.344del)': 'VHL',
    'VHL L153P (c.458T>C)': 'VHL',
    'TCF3::HLF Fusion': 'HLF;TCF3',
    'BRD4::NUTM1 Fusion': 'BRD4;NUTM1',
    'ALK I1171T': 'ALK',
    'DICER1 D1709E': 'DICER1',
    'ZMYM2::FGFR1 Fusion OR BCR::FGFR1 Fusion OR CEP43::FGFR1 Fusion OR TRIM24::FGFR1 Fusion OR FGFR1 Translocation':
        'BCR;CEP43;FGFR1;TRIM24;ZMYM2',  
    'VHL K196fs (c.584_585delAG)': 'VHL',
    'VHL N150fs (c.445_458del)': 'VHL',
    'VHL R60FS (c.179delG)': 'VHL',
    'TYMS RS34743033': 'TYMS',
    'LEPR UNDEREXPRESSION': 'LEPR',
    'FLT3 Amplification': 'FLT3',
    'VHL L158P (c.473T>C)': 'VHL',
    'VHL S72fs (c.214del)': 'VHL',
    'ACVR1 R206H': 'ACVR1',
    'BRAF G596R': 'BRAF',
    'ACVR1 G328W': 'ACVR1',
    'VHL Q132* (c.394C>T)': 'VHL',
    'FGFR1 N546K': 'FGFR1',
    'SMO L412F': 'SMO',
    'VHL Q145* (c.433C>T)': 'VHL',
    'CDKN2A Mutation': 'CDKN2A',
    'VHL A56fs (c.164_165insA)': 'VHL',
    'BIRC3 TRUNCATING MUTATION': 'BIRC3',
    'TP53 P151H': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 N331S': 'ABL1;BCR',
    'KIT V560D': 'KIT',
    'BCR::ABL1 Fusion AND ABL1 G250E': 'ABL1;BCR',
    'TP53 R283H': 'TP53',
    'VHL L128R (c.383T>G)': 'VHL',
    'TP53 E286K': 'TP53',
    'ABL1 P-Loop Mutation': 'ABL1',
    'VHL E94* (c.280G>T)': 'VHL',
    'VHL R82P (c.245G>C)': 'VHL',
    'BRAF D594A': 'BRAF',
    'VHL C162F (c.485G>T)': 'VHL',
    'SMO D473H': 'SMO',
    'VHL I151T (c.452T>C)': 'VHL',
    'KIT K550_K559DEL': 'KIT',
    'CRBN Mutation': 'CRBN',
    'PML::RARA Fusion AND PML L218P': 'PML;RARA',
    'EGFR K806E': 'EGFR',
    'VHL H125fs (c.374insA)': 'VHL',
    'VHL A149fs (c.445delG)': 'VHL',
    'MYD88 L265P': 'MYD88',
    'VHL Y156* (c.468T>G)': 'VHL',
    'CHEK1 Overexpression': 'CHEK1',
    'PPP2R1A P179R': 'PPP2R1A',
    'BCR::ABL1 Fusion AND ABL1 E450Q': 'ABL1;BCR',
    'ATM C2488Y': 'ATM',
    'GNAS R201H': 'GNAS',
    'KIT V559D': 'KIT',
    'PIK3CA L938*': 'PIK3CA',
    'FGFR1 Internal Duplication': 'FGFR1',
    'VHL S80I (c.239G>T)': 'VHL',
    'ATRX Deletion': 'ATRX',
    'ACVR1 G328V': 'ACVR1',
    'ERBB2 V773A': 'ERBB2',
    'VHL Y98C (c.293A>G)': 'VHL',
    'VHL V66del (c.197_220del)': 'VHL',
    'TP53 V272G': 'TP53',
    'STRN3::JAK2 Fusion': 'JAK2;STRN3',
    'EWSR1::WT1 Fusion': 'EWSR1;WT1',
    'VHL G93S (c.277G>A)': 'VHL',
    'SMARCA4 MUTATION': 'SMARCA4',
    'TP53 Y163H': 'TP53',
    'TP53 G266R': 'TP53',
    'ETV6::RUNX1 Fusion': 'ETV6;RUNX1',
    'EGFR C797Y': 'EGFR',
    'KIT K550_W557del': 'KIT',
    'VHL *214C (c.641_642insC)': 'VHL',
    'VHL S111R (c.333C>G)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 A397P': 'ABL1;BCR',
    'TP53 P250L': 'TP53',
    'VHL E70K (c.208G>A)': 'VHL',
    'EGFR P753S': 'EGFR',
    'KIT V560DEL': 'KIT',
    'TP53 H178P': 'TP53',
    'DPYD RS67376798 HOMOZYGOSITY': 'DPYD',
    'BRAF V600 OR v::BRAF Fusion': 'BRAF',
    'VHL R107P (c.320G>C)': 'VHL',
    'TP53 P98S': 'TP53',
    'VHL G93V (c.278G>T)': 'VHL',
    'TP53 L257P': 'TP53',
    'NF1 Loss': 'NF1',
    'CENPC::ABL1 Fusion': 'ABL1;CENPC',
    'ERBB2 N857S': 'ERBB2',
    'VHL K196* (c.586A>T)': 'VHL',
    'TP53 M246L': 'TP53',
    'TP53 T125T': 'TP53',
    'VHL EXON 2-3 DELETION': 'VHL',
    'RBM15::MRTFA Fusion': 'MRTFA;RBM15',
    'AURKA Amplification': 'AURKA',
    'PTEN R173C': 'PTEN',
    'VHL E186* (c.556G>T)': 'VHL',
    'VHL L198Q (c.593T>A)': 'VHL',
    'ATM c.902-1G>T': 'ATM',
    'VHL F91L (c.273C>G)': 'VHL',
    'VHL S111N (c.332G>A)': 'VHL',
    'CDK6 EXPRESSION': 'CDK6',
    'SMARCB1 Loss': 'SMARCB1',
    'VHL N150fs (c.449del)': 'VHL',
    'ZNF430::JAK2 Fusion': 'JAK2;ZNF430',
    'VHL L188V (c.562C>G)': 'VHL',
    'TP53 Y126S': 'TP53',
    'TP53 H115Y': 'TP53',
    'PRPS1 D183E': 'PRPS1',
    'EGFR R831H': 'EGFR',
    'TP53 V157F': 'TP53',
    'VHL Q73* (c.217C>T)': 'VHL',
    'VHL Splice Site (c.464-1G>C)': 'VHL',
    'TP53 E68G': 'TP53',
    'AKT1 S473 Phosphorylation': 'AKT1',
    'NT5C2 R367Q': 'NT5C2',
    'BRAF P731T': 'BRAF',
    'VHL E94FS (c.279delC)': 'VHL',
    'MYB::QKI Fusion': 'MYB;QKI',
    'EGFR E734Q': 'EGFR',
    'FOXP1::ABL1 Fusion': 'ABL1;FOXP1',
    'KIT A829P': 'KIT',
    'TP53 H168Y': 'TP53',
    'GOLGA5::JAK2 Fusion': 'GOLGA5;JAK2',
    'VHL G114R (c.340G>C)': 'VHL',
    'VHL E70* (c.208G>T)': 'VHL',
    'DUSP6 EXPRESSION': 'DUSP6',
    'BRAF G606E': 'BRAF',
    'BCR::ABL1 Fusion AND ABL1 T315I': 'ABL1;BCR',
    'FUS::CREB3L2 Fusion': 'CREB3L2;FUS',
    'TP53 P177S': 'TP53',
    'SSBP2::JAK2 Fusion': 'JAK2;SSBP2',
    'TERF2::JAK2 Fusion': 'JAK2;TERF2',
    'CTNNB1 Exon 3 Mutation': 'CTNNB1',
    'MTAP Deletion': 'MTAP',
    'VHL D121G (c.362A>G)': 'VHL',
    'EML4::ALK e2::e20': 'ALK;EML4',
    'TP53 G279E': 'TP53',
    'BRAF G496A': 'BRAF',
    'VHL N131fs (c.390_391del)': 'VHL',
    'RFX3::JAK2 Fusion': 'JAK2;RFX3',
    'BCR::ABL1 Fusion AND ABL1 F317L': 'ABL1;BCR',
    'VHL T133fs (c.397del)': 'VHL',
    'KIT Exon 14 Mutation': 'KIT',
    'PRPS1 A190T': 'PRPS1',
    'OFD1::JAK2 Fusion': 'JAK2;OFD1',
    'H3-3A G34W': 'H3-3A',
    'ETV6::ABL1 Fusion': 'ABL1;ETV6',
    'VHL C77fs (c.230del)': 'VHL',
    'VHL Splice Site (c.464-1G>A)': 'VHL',
    'VHL A56FS (c.164_165insG)': 'VHL',
    'TP53 R72P': 'TP53',
    'VHL Splice Site (c.464-2A>T)': 'VHL',
    'CASP8 D302H': 'CASP8',
    'BRAF G464V': 'BRAF',
    'PRPS1 K176N': 'PRPS1',
    'TP53 Q144P': 'TP53',
    'VHL R177ins (c.531insCTGAGAGTAAAGCCTGAA)': 'VHL',
    'VHL Y175D (c.523T>G)': 'VHL',
    'HEY1::NCOA2 Fusion': 'HEY1;NCOA2',
    'TP53 N239S': 'TP53',
    'VHL Splice Site (c.464-2A>G)': 'VHL',
    'EGFR W731L': 'EGFR',
    'PRPS1 S103I': 'PRPS1',
    'CBLC EXPRESSION': 'CBLC',
    'VHL G114dup (c.342dupGGT)': 'VHL',
    'RCSD1::ABL2 Fusion': 'ABL2;RCSD1',
    'PIK3CA Q546K': 'PIK3CA',
    'AFAP1::NTRK2 Fusion': 'AFAP1;NTRK2',
    'VHL S65* (c.194C>A)': 'VHL',
    'SMAD4 R361C': 'SMAD4',
    'SLCO1B1 N130D': 'SLCO1B1',
    'RANBP2::ALK Fusion': 'ALK;RANBP2',
    'TP53 V274F': 'TP53',
    'KIT F506_F508DUP': 'KIT',
    'PDGFRB Overexpression': 'PDGFRB',
    'VHL V130L (c.388G>C)': 'VHL',
    'BRAF Exon 15 Mutation': 'BRAF',
    'TCF3::PBX1 Fusion': 'PBX1;TCF3',
    'KIT W557_K558del': 'KIT',
    'KANK4::ALK Fusion': 'ALK;KANK4',
    'CHEK2 IVS2+1G>A': 'CHEK2',
    'BRAF V600E AND BRAF Amplification': 'BRAF',  
    'RAD50 L1237F': 'RAD50',
    'ACVR1 G328E': 'ACVR1',
    'MSH2 Loss OR MLH1 Loss': 'MLH1;MSH2',
    'NTRK1 Overexpression': 'NTRK1',
    'BCR::ABL1 Fusion AND ABL1 E453K': 'ABL1;BCR',
    'VHL V170F (c.508G>T)': 'VHL',
    'VHL C162R (c.484T>C)': 'VHL',
    'BCOR::CCNB3 Fusion': 'BCOR;CCNB3',
    'FOS::v Fusion': 'FOS',
    'VHL L85P (c.254T>C)': 'VHL',
    'VHL N150fs (c.448delA)': 'VHL',
    'TP53 L308M': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 E453A': 'ABL1;BCR',
    'TP53 E258K': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 L364I AND ABL1 M244V': 'ABL1;BCR',
    'ERBB2 Activating Mutation': 'ERBB2',
    'TP53 Y234H': 'TP53',
    'IKZF1 Loss-of-function': 'IKZF1',
    'KLF5 E419Q': 'KLF5',
    'VHL T157fs (c.472ins)': 'VHL',
    'RB1 Mutation': 'RB1',
    'TP53 D259V': 'TP53',
    'PRPS1 A87T': 'PRPS1',
    'KIT D816H': 'KIT',
    'BCR::ABL1 Fusion AND ABL1 F317I': 'ABL1;BCR',
    'CHD7::BEND2 Fusion': 'BEND2;CHD7',
    'PRPS1 M115T': 'PRPS1',
    'PDGFRA Exon 18 Mutation': 'PDGFRA',
    'VHL W88R (c.262T>A)': 'VHL',
    'TP53 L111R': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 S417Y': 'ABL1;BCR',
    'VHL L158V (c.472C>G)': 'VHL',
    'TP53 R181P': 'TP53',
    'v::FGFR1 Fusion': 'FGFR1',
    'BCR::ABL1 Fusion AND ABL1 D276G': 'ABL1;BCR',
    'FGFR3 G380R': 'FGFR3',
    'TP53 R181C': 'TP53',
    'SETBP1 Exon 4 Mutation': 'SETBP1',
    'BCL2 Mutation': 'BCL2',
    'MTOR C1483Y': 'MTOR',
    'PIK3CA Wildtype': 'PIK3CA',
    'TP53 R249S': 'TP53',
    'VHL L178Q (c.533T>A)': 'VHL',
    'TP53 G244S': 'TP53',
    'VHL Y175* (c.525delC)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 T315V': 'ABL1;BCR',
    'KIT P551_E554delPMYE': 'KIT',
    'SMU1::JAK2 Fusion': 'JAK2;SMU1',
    'VHL W117fs (c.349dup)': 'VHL',
    'ATM L2427P': 'ATM',
    'H3-3B K36M': 'H3-3B',
    'GNA11 Q209L': 'GNA11',
    'VHL S72P (c.214T>C)': 'VHL',
    'ABL1 V379I': 'ABL1',
    'VHL Splice Site (c.340+1G>A)': 'VHL',
    'FGFR3 K650D': 'FGFR3',
    'NF2 c.1396C>T': 'NF2',
    'BCR::ABL1 Fusion AND ABL1 V299L': 'ABL1;BCR',
    'FOXL2 C134W': 'FOXL2',
    'TP53 E224K': 'TP53',
    'VHL H115R (c.344A>G)': 'VHL',
    'VHL R82_V84del (c.244_252del)': 'VHL',
    'TP53 L323P': 'TP53',
    'NUP214::ABL1 Fusion': 'ABL1;NUP214',
    'VHL S65W (c.194C>G)': 'VHL',
    'VHL R167P (c.500G>C)': 'VHL',
    'VHL F76S (c.227T>C)': 'VHL',
    'NT5C2 D407A': 'NT5C2',
    'VHL P86S (c.256C>T)': 'VHL',
    'ZFTA::NCOA1 Fusion': 'NCOA1;ZFTA',
    'VHL V155G (c.464T>G)': 'VHL',
    'HRAS Q61': 'HRAS',
    'TSC1 R1062W': 'TSC1',
    'TP53 P278S': 'TP53',
    "EPCAM 3' Exon Deletion": 'EPCAM',
    'VHL S80fs (c.239del)': 'VHL',
    'CK High': '',  
    'VHL Exon 1 Deletion': 'VHL',
    'VHL G144fs (c.432insG)': 'VHL',
    'SF3B1 Mutation': 'SF3B1',
    'ERCC5 RS751402': 'ERCC5',
    'MN1::BEND2 Fusion': 'BEND2;MN1',
    'MN1::ZFTA Fusion': 'MN1;ZFTA',
    'Methylation signature ST-EPN-ZFTA': '',  
    'EPAS1 Overexpression': 'EPAS1',
    'H3-3A G34R': 'H3-3A',
    'VHL G114S (c.340G>A)': 'VHL',
    'VHL L178P (c.532C>T)': 'VHL',
    'YAP1::FAM118B Fusion': 'FAM118B;YAP1',
    'BRAF DEL 485-490': 'BRAF',
    'NAPRT Promoter Hypermethylation': 'NAPRT',
    'BRAF G469A': 'BRAF',
    'TP53 G266V': 'TP53',
    'PAX8 Expression': 'PAX8',
    'VHL G93R (c.277G>C)': 'VHL',
    'KIT Exon 9 Mutation': 'KIT',
    'VHL S111FS (c.331delA)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 T315A': 'ABL1;BCR',
    'TP53 P177F': 'TP53',
    'ATM K468FS': 'ATM',
    'BCR::ABL1 Fusion AND ABL1 E453Q': 'ABL1;BCR',
    'BCR::ABL1 Fusion AND ABL1 H396P': 'ABL1;BCR',
    'PRPS1 S103N': 'PRPS1',
    'VHL R120fs (c.358_359insAC)': 'VHL',
    'VHL Exon 1-2 Deletion': 'VHL',
    'PLCG2 MUTATION': 'PLCG2',
    'EZH2 Y646F': 'EZH2',
    'EGFR V851I': 'EGFR',
    'VHL V62Cfs*5 (c.180del)': 'VHL',
    'U2AF1 Q157P/R': 'U2AF1',
    'VHL L188P (c.563T>C)': 'VHL',
    'TP53 P98L': 'TP53',
    'PAX5 P80R': 'PAX5',
    'VHL Y98H (c.292T>C)': 'VHL',
    'TP53 R158L': 'TP53',
    'VHL D126FS (c.375_376insC)': 'VHL',
    'ERBB2 T798I': 'ERBB2',
    'VHL L118fs (c.352_353insA)': 'VHL',
    'VHL K159fs (c.474_476delGAAinsC)': 'VHL',
    'TP53 R158G': 'TP53',
    'GNA11 Q209': 'GNA11',
    'VHL L188Q (c.563T>A)': 'VHL',
    'IGH::CRLF2 Fusion': 'CRLF2;IGH',
    'KIT Amplification': 'KIT',
    'TP53 G262D': 'TP53',
    'PIK3CA E81K': 'PIK3CA',
    'VHL N131T (c.392A>C)': 'VHL',
    'ZFTA::NCOA2 Fusion': 'NCOA2;ZFTA',
    'PDGFRA D842_I843delinsVM': 'PDGFRA',
    'BCR::ABL1 Fusion AND ABL1 F486S': 'ABL1;BCR',
    'ABL2 W469C': 'ABL2',
    'FGFR3 K650Q': 'FGFR3',
    'BCR::ABL1 Fusion AND ABL1 F359C': 'ABL1;BCR',
    'PIK3R2 Overexpression': 'PIK3R2',
    'POT1 MUTATION': 'POT1',
    'VHL G104V (c.311G>T)': 'VHL',
    'EGFR R222C': 'EGFR',
    'FIP1L1::PDGFRA Fusion AND PDGFRA T674I': 'FIP1L1;PDGFRA',
    'VHL G144* (c.430G>T)': 'VHL',
    'v::JAK2 Fusion': 'JAK2',
    'KMT2D Loss-of-function': 'KMT2D',
    'EGFR T785A': 'EGFR',
    'KIT Y823D': 'KIT',
    'BCR::ABL1 Fusion AND ABL1 L248R AND ABL1 F359I': 'ABL1;BCR',
    'PDGFRA V561D': 'PDGFRA',
    'BCR::ABL1 Fusion AND ABL1 N146S': 'ABL1;BCR',
    'ECSCR EXPRESSION': 'ECSCR',
    'VHL *214G (c.640T>G)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 F317V': 'ABL1;BCR',
    'VHL T157I (c.470C>T)': 'VHL',
    'VHL S65A (c.193T>G)': 'VHL',
    'BRAF V600E OR NRAS Mutation OR HRAS Mutation OR KRAS Mutation OR NF1 Inactivating Mutation':
        'BRAF;HRAS;KRAS;NF1;NRAS',
    'ETV6::NTRK1 Fusion': 'ETV6;NTRK1',
    'VHL Q96_P97delinsH (c.288_290del)': 'VHL',
    'H3-3A MUTATION': 'H3-3A',
    'VHL P81S (c.241C>T)': 'VHL',
    'BRAF A598V': 'BRAF',
    'CCND3 Loss': 'CCND3',
    'VHL F136C (c.407T>G)': 'VHL',
    'CYP2D6 Loss-of-function': 'CYP2D6',
    'SMAD2 S276L': 'SMAD2',
    'VHL R82_V84del (c.243_251del)': 'VHL',
    'VHL V181fs (c.540_543del)': 'VHL',
    'VHL E160fs (c.479_480delAG)': 'VHL',
    'U2AF1 S34Y/F': 'U2AF1',
    'MACF1::BRAF Fusion': 'BRAF;MACF1',
    'EZH2 Y646C': 'EZH2',
    'VHL L89P (c.266T>C)': 'VHL',
    'VHL N78S (c.233A>G)': 'VHL',
    'VHL N78T (c.233A>C)': 'VHL',
    'VHL Y156N (c.466T>A)': 'VHL',
    'VHL T105P (c.313A>C)': 'VHL',
    'PRPS1 D139G': 'PRPS1',
    'KRAS A146': 'KRAS',
    'EZH2 Y646N': 'EZH2',
    'TP53 C238Y': 'TP53',
    'MLH1 *757L': 'MLH1',
    'VHL L178R (c.533T>G)': 'VHL',
    'ATM F1025L': 'ATM',
    'BTK T316A': 'BTK',
    'VCL::NTRK2 Fusion': 'NTRK2;VCL',
    'VHL *214C (c.642A>T)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 E255K': 'ABL1;BCR',
    'BRAF G463E': 'BRAF',
    'EZH2 Y646S OR EZH2 Y646F OR EZH2 Y646H OR EZH2 Y646C OR EZH2 Y646N OR EZH2 A692V OR EZH2 A682G': 'EZH2',
    'TRIM63::NTRK1 Fusion': 'NTRK1;TRIM63',
    'VHL N131K (c.393C>A)': 'VHL',
    'VHL P61FS (c.182_185delCCGT)': 'VHL',
    'PML::RARA Fusion': 'PML;RARA',
    'KIT D579del': 'KIT',
    'TP53 R280T': 'TP53',
    'KIT Wildtype': 'KIT',
    'LSM14A::ABL1 Fusion': 'ABL1;LSM14A',
    'KRAS Wildtype': 'KRAS',
    'VHL V155E (c.464T>A)': 'VHL',
    'VHL L135* (c.404T>A)': 'VHL',
    'CTNNB1 S45F': 'CTNNB1',
    'VHL P25L (c.74C>T)': 'VHL',
    'RET Mutation': 'RET',
    'ZFTA::MAML2 Fusion': 'MAML2;ZFTA',
    'LMNA::NTRK1 Fusion AND NTRK1 G595R AND NTRK1 F589L': 'LMNA;NTRK1',
    'VHL F76fs (c.223_224insT)': 'VHL',
    'NPM1::ALK Fusion': 'ALK;NPM1',
    'VHL P103FS (c.309_310delTG)': 'VHL',
    'VHL G93D (c.278G>A)': 'VHL',
    'MN1 Rearrangement': 'MN1',
    'EGFR E868G': 'EGFR',
    'BRAF D594V': 'BRAF',
    'VHL P61fs (c.183insC)': 'VHL',
    'ZMYM2::FGFR1 Fusion': 'FGFR1;ZMYM2',
    'KIT D816E': 'KIT',
    'ROBO4 EXPRESSION': 'ROBO4',
    'VHL V194fs (c.581_582del)': 'VHL',
    'EGFR V774M': 'EGFR',
    'CD44 CD44s Expression': 'CD44',  
    'VHL P86L (c.257C>T)': 'VHL',
    'DICER1 D1709G': 'DICER1',
    'KIT S628N': 'KIT',
    'MYB Truncation': 'MYB',
    'VHL Y175* (c.525C>A)': 'VHL',
    'VHL Q164L (c.491A>T)': 'VHL',
    'VHL Splice Site (c.464-1G>T)': 'VHL',
    'COL1A1::PDGFB Fusion': 'COL1A1;PDGFB',
    'BRAF V600E OR KIAA1549::BRAF Fusion': 'BRAF;KIAA1549',
    'CHEK2 Loss-of-function': 'CHEK2',
    'VHL R113* (c.337C>T)': 'VHL',
    'MTOR Mutation OR PIK3CA Mutation OR PTEN Mutation OR AKT1 Mutation OR AKT2 Mutation': 'AKT1;AKT2;MTOR;PIK3CA;PTEN',
    'VHL c.−213− ?_463 ?del': 'VHL',  
    'TP53 P219H': 'TP53',
    'VHL P102fs (c.305delC)': 'VHL',
    'ATM c.7515+1_2del': 'ATM',
    'TP53 R282W': 'TP53',
    'BCR::ABL1 Fusion AND ABL1 E292V': 'ABL1;BCR',
    'TP53 Y126D': 'TP53',
    'VHL L128F (c.382C>T)': 'VHL',
    'ZEB1 Expression': 'ZEB1',
    'KIT V654A': 'KIT',
    'CDKN1A rs1059234': 'CDKN1A',
    'ACTB::GLI1 Fusion': 'ACTB;GLI1',
    'VHL V166F (c.496G>T)': 'VHL',
    'BTK MUTATION': 'BTK',
    'VHL Q73FS (c.217delC)': 'VHL',
    'FBXW7 Loss-of-function': 'FBXW7',
    'ERBB2 T798M': 'ERBB2',
    'ACVR1 Mutation': 'ACVR1',
    'NT5C2 S445F': 'NT5C2',
    'CBFA2T3::GLIS2 Fusion': 'CBFA2T3;GLIS2',
    'TP53 L330P': 'TP53',
    'VHL c.341-59_341-14del': 'VHL',
    'VHL C77_N78insL (c.230_231insTCT)': 'VHL',
    'v::NUTM1 Fusion': 'NUTM1',
    'CCND1 Amplification OR CCND2 Amplification OR CCND3 Amplification': 'CCND1;CCND2;CCND3',
    'FGFR3 K650M': 'FGFR3',
    'VHL V87fs (c.259_260insA)': 'VHL',
    'VHL H115Q (c.345C>A)': 'VHL',
    'VHL R64P (c.191G>C)': 'VHL',
    'SMARCB1 Deletion': 'SMARCB1',
    'EWSR1::CREB3L1 Fusion': 'CREB3L1;EWSR1',
    'VHL G114Vfs*45 (c.339delA)': 'VHL',
    'ATM E2187*': 'ATM',
    'SNX29::JAK2 Fusion': 'JAK2;SNX29',
    'VHL L158fs (c.471dupT)': 'VHL',
    'KIT K558delinsNP': 'KIT',
    'VHL R161Q (c.482G>A)': 'VHL',
    'PDGFRA Overexpression': 'PDGFRA',
    'BCR::ABL1 Fusion AND ABL1 Q300R': 'ABL1;BCR',
    'KIT V560_L576DEL': 'KIT',
    'DDR2::NTRK1 Fusion': 'DDR2;NTRK1',
    'HIF1A EXPRESSION': 'HIF1A',
    'ARID1A P1175FS*5': 'ARID1A',
    'VHL L129fs (c.384delT)': 'VHL',
    'VHL H115Q (c.345C>G)': 'VHL',
    'BCR::ABL1 Fusion AND ABL1 F317C': 'ABL1;BCR',
    'TP53 P177H': 'TP53',
    'VHL S80R (c.240T>G)': 'VHL',
    'VHL W88FS (c.263_265delGGCinsTT)': 'VHL',
    'v::NTRK2 Fusion': 'NTRK2',
}


import re

def map_molecular_profile_to_genes(profiles):
    gene_pattern = re.compile(r'^([A-Z0-9]+(?:-[A-Z0-9]+)*)')
    result = {}
    for profile in profiles:
        genes = set()
        
        parts = re.split(r'\s+(?:AND|OR)\s+', profile)
        for part in parts:
            part = part.strip()
            if '::' in part:
                
                for gene_str in part.split('::'):
                    m = gene_pattern.match(gene_str)
                    if m:
                        genes.add(m.group(1))
            else:
                
                m = gene_pattern.match(part)
                if m:
                    genes.add(m.group(1))

        if not genes:
            
            pass
        if len(genes) > 1:
            
            pass
        result[profile] = ";".join(sorted(genes))
    if 'Kataegis Positive' in result.keys():
        result['Kataegis Positive'] = '' 
    return result


def compare_two_mappings(mapping1, mapping2):
    assert np.unique(list(mapping1.keys())).shape[0]==len(list(mapping1.keys()))
    assert all(np.unique(list(mapping1.keys()))==np.unique(list(mapping2.keys())))
    def normalize(value: str) -> set[str]:
        
        return {part.strip() for part in value.split(';') if part.strip()}
    for k, v in mapping1.items():
        try:
            a = normalize(v)
            b = normalize(mapping2[k])
            if a != b:
                print(f"Mismatch for {k}: {a} != {b}")
        except:
            print("BUGGED for key:", k)

